/**
 * Generated by tsnapi — public API snapshot of `@stream-markdown/math`
 */
// #region Interfaces
export interface KatexCdnLoaderOptions {
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
}
export interface KatexRuntime {
  installed: Promise<boolean>;
  preload: () => Promise<void>;
  dispose: () => void;
  ensureCss: () => void;
  getKatex: () => Promise<typeof import('katex')>;
  renderToHtml: (_: string, _?: RenderMathOptions) => Promise<{
    html?: string;
    error?: string;
  }>;
}
export interface MathExtensionOptions<TErrorComponent = never> extends MathRuntimeOptions {
  config?: KatexOptions$1;
  errorComponent?: TErrorComponent;
}
export interface MathRuntimeOptions {
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
}
export interface RenderMathOptions {
  displayMode?: boolean;
  config?: KatexOptions$1;
}
// #endregion

// #region Functions
export declare function createKatexCdnLoader(_?: KatexCdnLoaderOptions): {
  getCdnUrl: () => string | undefined;
  loadCdn: () => Promise<typeof import("katex") | undefined>;
  getCdnCssUrl: () => string | undefined;
  loadCss: () => void;
};
export declare function createKatexRuntime(_?: MathRuntimeOptions): KatexRuntime;
export declare function math<TErrorComponent = never>(_?: MathExtensionOptions<TErrorComponent>): MathExtension<ComarkPlugin<any, any>, TErrorComponent>;
// #endregion

// #region Variables
export declare const KATEX_VERSION: string;
// #endregion

// #region Other
export { KatexOptions }
export { MaybeGetter }
// #endregion