packages:
  - .
  - playground
  - docs

catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.2
    tsdown: ^0.17.2
    unplugin-icons: ^22.5.0
    unplugin-lightningcss: ^0.4.3
    vite: ^7.2.7
  cli:
    bumpp: ^10.3.2
    pncat: ^0.7.7
    taze: ^19.9.2
  dev:
    '@nuxt/devtools': ^3.1.1
    '@nuxtjs/color-mode': ^4.0.0
    happy-dom: ^20.0.11
    nuxt: ^4.2.2
    treechop: ^0.1.2
  docs:
    vitepress: ^1.6.4
  frontend:
    '@floating-ui/vue': ^1.1.9
    '@monaco-editor/loader': ^1.7.0
    echarts: ^6.0.0
    vue: ^3.5.25
    vue-json-pretty: ^2.6.0
  icons:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/lucide': ^1.2.79
  lint:
    '@antfu/eslint-config': ^6.6.1
    '@nuxt/eslint': ^1.12.1
    '@unocss/eslint-plugin': 66.5.9
    eslint: ^9.39.1
    eslint-plugin-format: ^1.1.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  markdown:
    markdown-it-async: ^2.2.0
    remend: ^1.0.1
  parser:
    mdast-util-from-markdown: ^2.0.2
    mdast-util-frontmatter: ^2.0.1
    mdast-util-gfm: ^3.1.0
    mdast-util-math: ^3.0.0
    mdast-util-to-markdown: ^2.1.2
    micromark-extension-cjk-friendly: ^1.2.3
    micromark-extension-cjk-friendly-gfm-strikethrough: ^1.2.3
    micromark-extension-frontmatter: ^2.0.0
    micromark-extension-gfm: ^3.0.0
    micromark-extension-math: ^3.1.0
    micromark-util-types: ^2.0.2
  prod:
    lz-string: ^1.5.0
  script:
    tsx: ^4.21.0
  style:
    '@unocss/nuxt': ^66.5.10
    '@unocss/reset': ^66.5.10
    clsx: ^2.1.1
    tailwind-merge: ^3.4.0
    unocss: ^66.5.10
  syntax:
    '@shikijs/monaco': ^3.19.0
  test:
    '@vue/test-utils': ^2.4.6
    vitest: ^4.0.15
  tsc:
    typescript: ^5.9.3
    vue-tsc: ^3.1.8
  types:
    '@types/node': ^24.10.3
  utils:
    '@antfu/utils': ^9.3.0
    '@vueuse/core': ^14.1.0
    '@vueuse/nuxt': ^14.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - vue-demi
  - '@parcel/watcher'
  - unrs-resolver
