/**
 * Generated by tsnapi — public API snapshot of `@stream-markdown/mermaid`
 */
// #region Interfaces
export interface MermaidCdnLoaderOptions {
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
}
export interface MermaidExtensionOptions<TErrorComponent = never> extends Omit<MermaidRuntimeOptions, 'isDark'> {
  errorComponent?: TErrorComponent;
}
export interface MermaidParseResult {
  valid: boolean;
  error?: string;
}
export interface MermaidRenderResult {
  svg?: string;
  error?: string;
  valid: boolean;
}
export interface MermaidRuntime {
  installed: Promise<boolean>;
  preload: () => Promise<void>;
  load: () => Promise<void>;
  dispose: () => void;
  parse: (_: string) => Promise<MermaidParseResult>;
  render: (_: string) => Promise<MermaidRenderResult>;
}
export interface MermaidRuntimeOptions {
  theme?: MaybeGetter<[string, string] | undefined>;
  config?: MaybeGetter<MermaidConfig$1 | undefined>;
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
  isDark?: MaybeGetter<boolean | undefined>;
}
// #endregion

// #region Functions
export declare function createMermaidCdnLoader(_?: MermaidCdnLoaderOptions): {
  getCdnUrl: () => string | undefined;
  loadCdn: () => Promise<typeof import("mermaid") | undefined>;
};
export declare function createMermaidRuntime(_?: MermaidRuntimeOptions): MermaidRuntime;
export declare function mermaid<TErrorComponent = never>(_?: MermaidExtensionOptions<TErrorComponent>): MermaidExtension<TErrorComponent>;
// #endregion

// #region Variables
export declare const DEFAULT_MERMAID_THEME: readonly ["neutral", "dark"];
export declare const MERMAID_VERSION: string;
// #endregion

// #region Other
export { MaybeGetter }
export { MermaidConfig }
// #endregion