/**
 * Generated by tsnapi — public API snapshot of `@stream-markdown/code`
 */
// #region Interfaces
export interface CodeRuntimeOptions {
  lang?: MaybeGetter<string | undefined>;
  isDark?: MaybeGetter<boolean | undefined>;
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
  theme?: MaybeGetter<[BuiltinTheme, BuiltinTheme] | undefined>;
  langs?: MaybeGetter<BundledLanguage[] | undefined>;
  langAlias?: MaybeGetter<Record<string, string> | undefined>;
  engine?: MaybeGetter<ShikiEngine | undefined>;
  codeToTokenOptions?: MaybeGetter<CodeToTokensOptions<BundledLanguage, BundledTheme> | undefined>;
}
export interface ShikiCdnLoaderOptions {
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
}
export interface ShikiRuntime {
  installed: Promise<boolean>;
  preload: () => Promise<void>;
  dispose: () => void;
  getShiki: () => Promise<typeof import('shiki')>;
  getHighlighter: () => Promise<Highlighter>;
  codeToTokens: (_: string) => Promise<TokensResult>;
  getLanguage: () => Promise<BuiltinLanguage>;
}
// #endregion

// #region Types
export type CodeExtensionOptions = Omit<CodeRuntimeOptions, 'isDark' | 'lang'>;
export type ShikiEngine = MaybePromise<RegexEngine>;
// #endregion

// #region Functions
export declare function code(_?: CodeExtensionOptions): CodeExtension;
export declare function createShikiCdnLoader(_?: ShikiCdnLoaderOptions): {
  getCdnUrl: () => string | undefined;
  loadCdn: () => Promise<typeof import("shiki") | undefined>;
};
export declare function createShikiRuntime(_?: CodeRuntimeOptions): ShikiRuntime;
export declare function disposeShikiHighlighter(): void;
export declare function resolveShikiEngine(_: CodeRuntimeOptions['engine']): Promise<RegexEngine>;
// #endregion

// #region Variables
export declare const SHIKI_VERSION: string;
// #endregion

// #region Other
export { DEFAULT_SHIKI_DARK_THEME }
export { DEFAULT_SHIKI_LIGHT_THEME }
export { LANGUAGE_ALIAS }
export { LANGUAGE_EXTENSIONS }
export { MaybeGetter }
// #endregion