import type { BuiltinLanguage, SpecialLanguage } from 'shiki'
import type { Component } from 'vue'
import { defineAsyncComponent } from 'vue'

export const DEFAULT_LIGHT_THEME = 'github-light'
export const DEFAULT_DARK_THEME = 'github-dark'

/// keep-sorted
export const LANGUAGE_ALIAS: Record<string, BuiltinLanguage> = {}

/// keep-sorted
export const LANGUAGE_EXTENSIONS: Partial<Record<BuiltinLanguage, string>> = {
  '1c-query': '1cq',
  '1c': '1c',
  'abap': 'abap',
  'actionscript-3': 'as',
  'ada': 'ada',
  'adoc': 'adoc',
  'angular-html': 'html',
  'angular-ts': 'ts',
  'apache': 'conf',
  'apex': 'cls',
  'apl': 'apl',
  'applescript': 'applescript',
  'ara': 'ara',
  'asciidoc': 'adoc',
  'asm': 'asm',
  'astro': 'astro',
  'awk': 'awk',
  'ballerina': 'bal',
  'bash': 'sh',
  'bat': 'bat',
  'batch': 'bat',
  'be': 'be',
  'beancount': 'beancount',
  'berry': 'berry',
  'bibtex': 'bib',
  'bicep': 'bicep',
  'blade': 'blade.php',
  'bsl': 'bsl',
  'c': 'c',
  'c#': 'cs',
  'c++': 'cpp',
  'cadence': 'cdc',
  'cairo': 'cairo',
  'cdc': 'cdc',
  'clarity': 'clar',
  'clj': 'clj',
  'clojure': 'clj',
  'closure-templates': 'soy',
  'cmake': 'cmake',
  'cmd': 'cmd',
  'cobol': 'cob',
  'codeowners': 'CODEOWNERS',
  'codeql': 'ql',
  'coffee': 'coffee',
  'coffeescript': 'coffee',
  'common-lisp': 'lisp',
  'console': 'sh',
  'coq': 'v',
  'cpp': 'cpp',
  'cql': 'cql',
  'crystal': 'cr',
  'cs': 'cs',
  'csharp': 'cs',
  'css': 'css',
  'csv': 'csv',
  'cue': 'cue',
  'cypher': 'cql',
  'd': 'd',
  'dart': 'dart',
  'dax': 'dax',
  'desktop': 'desktop',
  'diff': 'diff',
  'docker': 'dockerfile',
  'dockerfile': 'dockerfile',
  'dotenv': 'env',
  'dream-maker': 'dm',
  'edge': 'edge',
  'elisp': 'el',
  'elixir': 'ex',
  'elm': 'elm',
  'emacs-lisp': 'el',
  'erb': 'erb',
  'erl': 'erl',
  'erlang': 'erl',
  'f': 'f',
  'f#': 'fs',
  'f03': 'f03',
  'f08': 'f08',
  'f18': 'f18',
  'f77': 'f77',
  'f90': 'f90',
  'f95': 'f95',
  'fennel': 'fnl',
  'fish': 'fish',
  'fluent': 'ftl',
  'for': 'for',
  'fortran-fixed-form': 'f',
  'fortran-free-form': 'f90',
  'fs': 'fs',
  'fsharp': 'fs',
  'fsl': 'fsl',
  'ftl': 'ftl',
  'gdresource': 'tres',
  'gdscript': 'gd',
  'gdshader': 'gdshader',
  'genie': 'gs',
  'gherkin': 'feature',
  'git-commit': 'gitcommit',
  'git-rebase': 'gitrebase',
  'gjs': 'js',
  'gleam': 'gleam',
  'glimmer-js': 'js',
  'glimmer-ts': 'ts',
  'glsl': 'glsl',
  'gnuplot': 'plt',
  'go': 'go',
  'gql': 'gql',
  'graphql': 'graphql',
  'groovy': 'groovy',
  'gts': 'gts',
  'hack': 'hack',
  'haml': 'haml',
  'handlebars': 'hbs',
  'haskell': 'hs',
  'haxe': 'hx',
  'hbs': 'hbs',
  'hcl': 'hcl',
  'hjson': 'hjson',
  'hlsl': 'hlsl',
  'hs': 'hs',
  'html-derivative': 'html',
  'html': 'html',
  'http': 'http',
  'hxml': 'hxml',
  'hy': 'hy',
  'imba': 'imba',
  'ini': 'ini',
  'jade': 'jade',
  'java': 'java',
  'javascript': 'js',
  'jinja': 'jinja',
  'jison': 'jison',
  'jl': 'jl',
  'js': 'js',
  'json': 'json',
  'json5': 'json5',
  'jsonc': 'jsonc',
  'jsonl': 'jsonl',
  'jsonnet': 'jsonnet',
  'jssm': 'jssm',
  'jsx': 'jsx',
  'julia': 'jl',
  'kotlin': 'kt',
  'kql': 'kql',
  'kt': 'kt',
  'kts': 'kts',
  'kusto': 'kql',
  'latex': 'tex',
  'lean': 'lean',
  'lean4': 'lean',
  'less': 'less',
  'liquid': 'liquid',
  'lisp': 'lisp',
  'lit': 'lit',
  'llvm': 'll',
  'log': 'log',
  'logo': 'logo',
  'lua': 'lua',
  'luau': 'luau',
  'make': 'mak',
  'makefile': 'mak',
  'markdown': 'md',
  'marko': 'marko',
  'matlab': 'm',
  'md': 'md',
  'mdc': 'mdc',
  'mdx': 'mdx',
  'mediawiki': 'wiki',
  'mermaid': 'mmd',
  'mips': 's',
  'mipsasm': 's',
  'mmd': 'mmd',
  'mojo': 'mojo',
  'move': 'move',
  'nar': 'nar',
  'narrat': 'narrat',
  'nextflow': 'nf',
  'nf': 'nf',
  'nginx': 'conf',
  'nim': 'nim',
  'nix': 'nix',
  'nu': 'nu',
  'nushell': 'nu',
  'objc': 'm',
  'objective-c': 'm',
  'objective-cpp': 'mm',
  'ocaml': 'ml',
  'pascal': 'pas',
  'perl': 'pl',
  'perl6': 'p6',
  'php': 'php',
  'plsql': 'pls',
  'po': 'po',
  'polar': 'polar',
  'postcss': 'pcss',
  'pot': 'pot',
  'potx': 'potx',
  'powerquery': 'pq',
  'powershell': 'ps1',
  'prisma': 'prisma',
  'prolog': 'pl',
  'properties': 'properties',
  'proto': 'proto',
  'protobuf': 'proto',
  'ps': 'ps',
  'ps1': 'ps1',
  'pug': 'pug',
  'puppet': 'pp',
  'purescript': 'purs',
  'py': 'py',
  'python': 'py',
  'ql': 'ql',
  'qml': 'qml',
  'qmldir': 'qmldir',
  'qss': 'qss',
  'r': 'r',
  'racket': 'rkt',
  'raku': 'raku',
  'razor': 'cshtml',
  'rb': 'rb',
  'reg': 'reg',
  'regex': 'regex',
  'regexp': 'regexp',
  'rel': 'rel',
  'riscv': 's',
  'rs': 'rs',
  'rst': 'rst',
  'ruby': 'rb',
  'rust': 'rs',
  'sas': 'sas',
  'sass': 'sass',
  'scala': 'scala',
  'scheme': 'scm',
  'scss': 'scss',
  'sdbl': 'sdbl',
  'sh': 'sh',
  'shader': 'shader',
  'shaderlab': 'shader',
  'shell': 'sh',
  'shellscript': 'sh',
  'shellsession': 'sh',
  'smalltalk': 'st',
  'solidity': 'sol',
  'soy': 'soy',
  'sparql': 'rq',
  'spl': 'spl',
  'splunk': 'spl',
  'sql': 'sql',
  'ssh-config': 'config',
  'stata': 'do',
  'styl': 'styl',
  'stylus': 'styl',
  'svelte': 'svelte',
  'swift': 'swift',
  'system-verilog': 'sv',
  'systemd': 'service',
  'talon': 'talon',
  'talonscript': 'talon',
  'tasl': 'tasl',
  'tcl': 'tcl',
  'templ': 'templ',
  'terraform': 'tf',
  'tex': 'tex',
  'tf': 'tf',
  'tfvars': 'tfvars',
  'toml': 'toml',
  'ts-tags': 'ts',
  'ts': 'ts',
  'tsp': 'tsp',
  'tsv': 'tsv',
  'tsx': 'tsx',
  'turtle': 'ttl',
  'twig': 'twig',
  'typ': 'typ',
  'typescript': 'ts',
  'typespec': 'tsp',
  'typst': 'typ',
  'v': 'v',
  'vala': 'vala',
  'vb': 'vb',
  'verilog': 'v',
  'vhdl': 'vhdl',
  'vim': 'vim',
  'viml': 'vim',
  'vimscript': 'vim',
  'vue-html': 'html',
  'vue-vine': 'vine',
  'vue': 'vue',
  'vy': 'vy',
  'vyper': 'vy',
  'wasm': 'wasm',
  'wenyan': 'wy',
  'wgsl': 'wgsl',
  'wiki': 'wiki',
  'wikitext': 'wiki',
  'wit': 'wit',
  'wl': 'wl',
  'wolfram': 'wl',
  'xml': 'xml',
  'xsl': 'xsl',
  'yaml': 'yaml',
  'yml': 'yml',
  'zenscript': 'zs',
  'zig': 'zig',
  'zsh': 'zsh',
  '文言': 'wy',
}

/// keep-sorted
export const LANGUAGE_ICONS: Partial<Record<BuiltinLanguage | SpecialLanguage, Component>> = {
  'adoc': defineAsyncComponent(() => import('~icons/catppuccin/asciidoc')),
  'angular-html': defineAsyncComponent(() => import('~icons/catppuccin/angular')),
  'angular-ts': defineAsyncComponent(() => import('~icons/catppuccin/angular-component')),
  'apache': defineAsyncComponent(() => import('~icons/catppuccin/apache')),
  'asciidoc': defineAsyncComponent(() => import('~icons/catppuccin/asciidoc')),
  'asm': defineAsyncComponent(() => import('~icons/catppuccin/assembly')),
  'astro': defineAsyncComponent(() => import('~icons/catppuccin/astro')),
  'bash': defineAsyncComponent(() => import('~icons/catppuccin/bash')),
  'bat': defineAsyncComponent(() => import('~icons/catppuccin/batch')),
  'batch': defineAsyncComponent(() => import('~icons/catppuccin/batch')),
  'bicep': defineAsyncComponent(() => import('~icons/catppuccin/bicep')),
  'c': defineAsyncComponent(() => import('~icons/catppuccin/c')),
  'c#': defineAsyncComponent(() => import('~icons/catppuccin/csharp')),
  'c++': defineAsyncComponent(() => import('~icons/catppuccin/cpp')),
  'cjs': defineAsyncComponent(() => import('~icons/catppuccin/javascript')),
  'clj': defineAsyncComponent(() => import('~icons/catppuccin/clojure')),
  'clojure': defineAsyncComponent(() => import('~icons/catppuccin/clojure')),
  'cmake': defineAsyncComponent(() => import('~icons/catppuccin/cmake')),
  'cmd': defineAsyncComponent(() => import('~icons/catppuccin/batch')),
  'cobol': defineAsyncComponent(() => import('~icons/catppuccin/cobol')),
  'codeowners': defineAsyncComponent(() => import('~icons/catppuccin/codeowners')),
  'coffee': defineAsyncComponent(() => import('~icons/catppuccin/coffeescript')),
  'coffeescript': defineAsyncComponent(() => import('~icons/catppuccin/coffeescript')),
  'cpp': defineAsyncComponent(() => import('~icons/catppuccin/cpp')),
  'crystal': defineAsyncComponent(() => import('~icons/catppuccin/crystal')),
  'cs': defineAsyncComponent(() => import('~icons/catppuccin/csharp')),
  'csharp': defineAsyncComponent(() => import('~icons/catppuccin/csharp')),
  'css': defineAsyncComponent(() => import('~icons/catppuccin/css')),
  'csv': defineAsyncComponent(() => import('~icons/catppuccin/csv')),
  'cts': defineAsyncComponent(() => import('~icons/catppuccin/typescript')),
  'cue': defineAsyncComponent(() => import('~icons/catppuccin/cue')),
  'd': defineAsyncComponent(() => import('~icons/catppuccin/d')),
  'dart': defineAsyncComponent(() => import('~icons/catppuccin/dart')),
  'diff': defineAsyncComponent(() => import('~icons/catppuccin/diff')),
  'docker': defineAsyncComponent(() => import('~icons/catppuccin/docker')),
  'dockerfile': defineAsyncComponent(() => import('~icons/catppuccin/docker')),
  'dotenv': defineAsyncComponent(() => import('~icons/catppuccin/env')),
  'elixir': defineAsyncComponent(() => import('~icons/catppuccin/elixir')),
  'elm': defineAsyncComponent(() => import('~icons/catppuccin/elm')),
  'erb': defineAsyncComponent(() => import('~icons/catppuccin/ruby')),
  'erl': defineAsyncComponent(() => import('~icons/catppuccin/erlang')),
  'erlang': defineAsyncComponent(() => import('~icons/catppuccin/erlang')),
  'f': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'f#': defineAsyncComponent(() => import('~icons/catppuccin/fsharp')),
  'f03': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'f08': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'f18': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'f77': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'f90': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'f95': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'for': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'fortran-fixed-form': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'fortran-free-form': defineAsyncComponent(() => import('~icons/catppuccin/fortran')),
  'fs': defineAsyncComponent(() => import('~icons/catppuccin/fsharp')),
  'fsharp': defineAsyncComponent(() => import('~icons/catppuccin/fsharp')),
  'git-commit': defineAsyncComponent(() => import('~icons/catppuccin/git')),
  'git-rebase': defineAsyncComponent(() => import('~icons/catppuccin/git')),
  'gleam': defineAsyncComponent(() => import('~icons/catppuccin/gleam')),
  'go': defineAsyncComponent(() => import('~icons/catppuccin/go')),
  'gql': defineAsyncComponent(() => import('~icons/catppuccin/graphql')),
  'graphql': defineAsyncComponent(() => import('~icons/catppuccin/graphql')),
  'groovy': defineAsyncComponent(() => import('~icons/catppuccin/groovy')),
  'haml': defineAsyncComponent(() => import('~icons/catppuccin/haml')),
  'handlebars': defineAsyncComponent(() => import('~icons/catppuccin/handlebars')),
  'haskell': defineAsyncComponent(() => import('~icons/catppuccin/haskell')),
  'haxe': defineAsyncComponent(() => import('~icons/catppuccin/haxe')),
  'hbs': defineAsyncComponent(() => import('~icons/catppuccin/handlebars')),
  'hs': defineAsyncComponent(() => import('~icons/catppuccin/haskell')),
  'html': defineAsyncComponent(() => import('~icons/catppuccin/html')),
  'http': defineAsyncComponent(() => import('~icons/catppuccin/http')),
  'jade': defineAsyncComponent(() => import('~icons/catppuccin/pug')),
  'java': defineAsyncComponent(() => import('~icons/catppuccin/java')),
  'javascript': defineAsyncComponent(() => import('~icons/catppuccin/javascript')),
  'jinja': defineAsyncComponent(() => import('~icons/catppuccin/jinja')),
  'jl': defineAsyncComponent(() => import('~icons/catppuccin/julia')),
  'js': defineAsyncComponent(() => import('~icons/catppuccin/javascript')),
  'json': defineAsyncComponent(() => import('~icons/catppuccin/json')),
  'json5': defineAsyncComponent(() => import('~icons/catppuccin/json')),
  'jsonc': defineAsyncComponent(() => import('~icons/catppuccin/json')),
  'jsonl': defineAsyncComponent(() => import('~icons/catppuccin/json')),
  'jsx': defineAsyncComponent(() => import('~icons/catppuccin/javascript')),
  'julia': defineAsyncComponent(() => import('~icons/catppuccin/julia')),
  'kdl': defineAsyncComponent(() => import('~icons/catppuccin/kdl')),
  'kotlin': defineAsyncComponent(() => import('~icons/catppuccin/kotlin')),
  'kt': defineAsyncComponent(() => import('~icons/catppuccin/kotlin')),
  'kts': defineAsyncComponent(() => import('~icons/catppuccin/kotlin')),
  'latex': defineAsyncComponent(() => import('~icons/catppuccin/latex')),
  'less': defineAsyncComponent(() => import('~icons/catppuccin/less')),
  'liquid': defineAsyncComponent(() => import('~icons/catppuccin/liquid')),
  'lisp': defineAsyncComponent(() => import('~icons/catppuccin/lisp')),
  'log': defineAsyncComponent(() => import('~icons/catppuccin/log')),
  'lua': defineAsyncComponent(() => import('~icons/catppuccin/lua')),
  'luau': defineAsyncComponent(() => import('~icons/catppuccin/luau')),
  'make': defineAsyncComponent(() => import('~icons/catppuccin/makefile')),
  'makefile': defineAsyncComponent(() => import('~icons/catppuccin/makefile')),
  'markdown': defineAsyncComponent(() => import('~icons/catppuccin/markdown')),
  'marko': defineAsyncComponent(() => import('~icons/catppuccin/marko')),
  'matlab': defineAsyncComponent(() => import('~icons/catppuccin/matlab')),
  'md': defineAsyncComponent(() => import('~icons/catppuccin/markdown')),
  'mdc': defineAsyncComponent(() => import('~icons/catppuccin/markdown')),
  'mdx': defineAsyncComponent(() => import('~icons/catppuccin/markdown')),
  'mermaid': defineAsyncComponent(() => import('~icons/catppuccin/mermaid')),
  'mjs': defineAsyncComponent(() => import('~icons/catppuccin/javascript')),
  'mmd': defineAsyncComponent(() => import('~icons/catppuccin/mermaid')),
  'mts': defineAsyncComponent(() => import('~icons/catppuccin/typescript')),
  'nextflow': defineAsyncComponent(() => import('~icons/catppuccin/nextflow')),
  'nf': defineAsyncComponent(() => import('~icons/catppuccin/nextflow')),
  'nginx': defineAsyncComponent(() => import('~icons/catppuccin/nginx')),
  'nim': defineAsyncComponent(() => import('~icons/catppuccin/nim')),
  'nix': defineAsyncComponent(() => import('~icons/catppuccin/nix')),
  'ocaml': defineAsyncComponent(() => import('~icons/catppuccin/ocaml')),
  'perl': defineAsyncComponent(() => import('~icons/catppuccin/perl')),
  'php': defineAsyncComponent(() => import('~icons/catppuccin/php')),
  'postcss': defineAsyncComponent(() => import('~icons/catppuccin/postcss')),
  'powershell': defineAsyncComponent(() => import('~icons/catppuccin/powershell')),
  'prisma': defineAsyncComponent(() => import('~icons/catppuccin/prisma')),
  'prolog': defineAsyncComponent(() => import('~icons/catppuccin/prolog')),
  'properties': defineAsyncComponent(() => import('~icons/catppuccin/properties')),
  'proto': defineAsyncComponent(() => import('~icons/catppuccin/proto')),
  'protobuf': defineAsyncComponent(() => import('~icons/catppuccin/proto')),
  'ps': defineAsyncComponent(() => import('~icons/catppuccin/powershell')),
  'ps1': defineAsyncComponent(() => import('~icons/catppuccin/powershell')),
  'pug': defineAsyncComponent(() => import('~icons/catppuccin/pug')),
  'puppet': defineAsyncComponent(() => import('~icons/catppuccin/puppet')),
  'py': defineAsyncComponent(() => import('~icons/catppuccin/python')),
  'python': defineAsyncComponent(() => import('~icons/catppuccin/python')),
  'r': defineAsyncComponent(() => import('~icons/catppuccin/r')),
  'racket': defineAsyncComponent(() => import('~icons/catppuccin/racket')),
  'razor': defineAsyncComponent(() => import('~icons/catppuccin/razor')),
  'rb': defineAsyncComponent(() => import('~icons/catppuccin/ruby')),
  'rs': defineAsyncComponent(() => import('~icons/catppuccin/rust')),
  'ruby': defineAsyncComponent(() => import('~icons/catppuccin/ruby')),
  'rust': defineAsyncComponent(() => import('~icons/catppuccin/rust')),
  'sass': defineAsyncComponent(() => import('~icons/catppuccin/sass')),
  'scala': defineAsyncComponent(() => import('~icons/catppuccin/scala')),
  'scheme': defineAsyncComponent(() => import('~icons/catppuccin/scheme')),
  'scss': defineAsyncComponent(() => import('~icons/catppuccin/sass')),
  'sh': defineAsyncComponent(() => import('~icons/catppuccin/bash')),
  'shader': defineAsyncComponent(() => import('~icons/catppuccin/shader')),
  'shell': defineAsyncComponent(() => import('~icons/catppuccin/bash')),
  'shellscript': defineAsyncComponent(() => import('~icons/catppuccin/bash')),
  'solidity': defineAsyncComponent(() => import('~icons/catppuccin/solidity')),
  'sql': defineAsyncComponent(() => import('~icons/catppuccin/database')),
  'stata': defineAsyncComponent(() => import('~icons/catppuccin/stata')),
  'styl': defineAsyncComponent(() => import('~icons/catppuccin/sass')),
  'stylus': defineAsyncComponent(() => import('~icons/catppuccin/sass')),
  'svelte': defineAsyncComponent(() => import('~icons/catppuccin/svelte')),
  'swift': defineAsyncComponent(() => import('~icons/catppuccin/swift')),
  'terraform': defineAsyncComponent(() => import('~icons/catppuccin/terraform')),
  'tex': defineAsyncComponent(() => import('~icons/catppuccin/latex')),
  'text': defineAsyncComponent(() => import('~icons/catppuccin/text')),
  'tf': defineAsyncComponent(() => import('~icons/catppuccin/terraform')),
  'tfvars': defineAsyncComponent(() => import('~icons/catppuccin/terraform')),
  'toml': defineAsyncComponent(() => import('~icons/catppuccin/toml')),
  'ts': defineAsyncComponent(() => import('~icons/catppuccin/typescript')),
  'tsv': defineAsyncComponent(() => import('~icons/catppuccin/csv')),
  'tsx': defineAsyncComponent(() => import('~icons/catppuccin/typescript')),
  'twig': defineAsyncComponent(() => import('~icons/catppuccin/twig')),
  'typ': defineAsyncComponent(() => import('~icons/catppuccin/typst')),
  'typescript': defineAsyncComponent(() => import('~icons/catppuccin/typescript')),
  'typst': defineAsyncComponent(() => import('~icons/catppuccin/typst')),
  'v': defineAsyncComponent(() => import('~icons/catppuccin/v')),
  'vala': defineAsyncComponent(() => import('~icons/catppuccin/vala')),
  'verilog': defineAsyncComponent(() => import('~icons/catppuccin/verilog')),
  'vim': defineAsyncComponent(() => import('~icons/catppuccin/vim')),
  'viml': defineAsyncComponent(() => import('~icons/catppuccin/vim')),
  'vimscript': defineAsyncComponent(() => import('~icons/catppuccin/vim')),
  'vue-html': defineAsyncComponent(() => import('~icons/catppuccin/vue')),
  'vue-vine': defineAsyncComponent(() => import('~icons/catppuccin/vue')),
  'vue': defineAsyncComponent(() => import('~icons/catppuccin/vue')),
  'xml': defineAsyncComponent(() => import('~icons/catppuccin/xml')),
  'xsl': defineAsyncComponent(() => import('~icons/catppuccin/xml')),
  'yaml': defineAsyncComponent(() => import('~icons/catppuccin/yaml')),
  'yml': defineAsyncComponent(() => import('~icons/catppuccin/yaml')),
  'zig': defineAsyncComponent(() => import('~icons/catppuccin/zig')),
  'zsh': defineAsyncComponent(() => import('~icons/catppuccin/bash')),
} as const
