export {
  ANIMATION_SPLITS,
  ANIMATION_TYPES,
  CARETS,
  DEFAULT_ANIMATION,
  DEFAULT_ANIMATION_SPLIT,
  DEFAULT_HARDEN_OPTIONS,
  DEFAULT_LANGUAGE,
  PLAIN_TEXT_NODES,
  PRELOAD_NODE_RENDERER,
  SHADCN_SCHEMAS,
  SUPPORT_LANGUAGES,
} from '@stream-markdown/core'
