/**
 * Generated by tsnapi — public API snapshot of `vue-stream-markdown`
 */
// #region Interfaces
export interface CodeBlockNode {
  value: string;
  lang?: string | null;
  meta?: string;
  loading?: boolean;
}
export interface ExtensionOverrides {
  beautifulMermaid?: Extensions['beautifulMermaid'] | false;
  code?: Extensions['code'] | false;
  math?: Extensions['math'] | false;
  mermaid?: Extensions['mermaid'] | false;
}
export interface MarkdownComponentProps {
  node: ElementNode;
}
export interface MarkdownControlContext<TNode = ElementNode> {
  node: TNode;
  nodeKey: string;
}
export interface MarkdownProviderContext {
  cssVariables: Ref<Record<string, string>> | ComputedRef<Record<string, string>>;
  extensions: ComputedRef<Extensions | undefined>;
  isDark: ComputedRef<boolean>;
}
export interface MarkdownProviderProps {
  extensions?: Extensions;
  isDark?: boolean;
  themeElement?: () => HTMLElement | undefined;
}
export interface MathRenderNode {
  value: string;
  display: boolean;
  loading?: boolean;
}
export interface MathRenderProps {
  node: MathRenderNode;
}
export interface StreamMarkdownProvideContext {
  controls?: MaybeRefOrGetter<StreamMarkdownContext['controls']>;
  previewers?: MaybeRefOrGetter<StreamMarkdownContext['previewers']>;
  extensions?: MaybeRefOrGetter<Extensions | undefined>;
  hardenOptions?: MaybeRefOrGetter<StreamMarkdownContext['hardenOptions']>;
  codeOptions?: MaybeRefOrGetter<StreamMarkdownContext['codeOptions']>;
  tableOptions?: MaybeRefOrGetter<TableOptions | undefined>;
  imageOptions?: MaybeRefOrGetter<StreamMarkdownContext['imageOptions']>;
  linkOptions?: MaybeRefOrGetter<StreamMarkdownContext['linkOptions']>;
  mode?: MaybeRefOrGetter<'static' | 'streaming'>;
  dir?: MaybeRefOrGetter<StreamMarkdownProps['dir']>;
  isDark?: MaybeRefOrGetter<boolean>;
  rootStyle?: MaybeRefOrGetter<Record<string, string>>;
  uiOptions?: MaybeRefOrGetter<UIOptions | undefined>;
  icons?: MaybeRefOrGetter<Icons>;
  uiComponents?: MaybeRefOrGetter<UIComponents>;
  enableAnimate?: MaybeRefOrGetter<boolean>;
  animation?: MaybeRefOrGetter<StreamMarkdownProps['animation']>;
  animationSplit?: MaybeRefOrGetter<StreamMarkdownProps['animationSplit']>;
  animationStagger?: MaybeRefOrGetter<StreamMarkdownProps['animationStagger']>;
  enableCaret?: MaybeRefOrGetter<boolean>;
  caret?: MaybeRefOrGetter<StreamMarkdownProps['caret']>;
  documentNodes?: MaybeRefOrGetter<Node[]>;
  getContainer?: () => HTMLElement | undefined;
  beforeDownload?: StreamMarkdownProps['beforeDownload'];
  onCopied?: (_: string) => void;
}
export interface StreamMarkdownResolvedContext {
  context: StreamMarkdownProvideContext;
  provideContext: (_: Partial<StreamMarkdownProvideContext>) => void;
  injectContext: () => StreamMarkdownProvideContext;
  mode: ComputedRef<'static' | 'streaming'>;
  dir: ComputedRef<StreamMarkdownProps['dir']>;
  controls: ComputedRef<StreamMarkdownContext['controls']>;
  previewers: ComputedRef<StreamMarkdownContext['previewers']>;
  extensions: ComputedRef<Extensions | undefined>;
  hardenOptions: ComputedRef<StreamMarkdownContext['hardenOptions']>;
  codeOptions: ComputedRef<StreamMarkdownContext['codeOptions']>;
  tableOptions: ComputedRef<TableOptions | undefined>;
  imageOptions: ComputedRef<StreamMarkdownContext['imageOptions']>;
  linkOptions: ComputedRef<StreamMarkdownContext['linkOptions']>;
  hideTooltip: ComputedRef<boolean>;
  icons: ComputedRef<Partial<Icons>>;
  uiComponents: ComputedRef<UIComponents>;
  isDark: ComputedRef<boolean>;
  rootStyle: ComputedRef<Record<string, string>>;
  enableAnimate: ComputedRef<boolean>;
  animation: ComputedRef<NonNullable<StreamMarkdownProps['animation']>>;
  animationSplit: ComputedRef<NonNullable<StreamMarkdownProps['animationSplit']>>;
  animationStagger: ComputedRef<number>;
  enableCaret: ComputedRef<boolean | undefined>;
  caret: ComputedRef<string | undefined>;
  documentNodes: ComputedRef<Node[]>;
  readonly getContainer: () => HTMLElement | undefined;
  readonly beforeDownload: NonNullable<StreamMarkdownProps['beforeDownload']>;
  readonly onCopied: (_: string) => void;
}
// #endregion

// #region Types
export type CodeBlockProps = MarkdownControlContext<CodeBlockNode>;
export type CodeControlsConfig = CodeControlsConfig$1<ControlTransformer<CodeBlockProps>>;
export type CodeOptions = CodeOptions$1<Component>;
export type CodeOptionsLanguage = CodeOptionsLanguage$1<Component>;
export type Control = Control$1<UIButtonProps>;
export type ControlsConfig = ControlsConfig$1<ControlTransformer<MarkdownControlContext>, ControlTransformer<CodeBlockProps>, ControlTransformer<MarkdownControlContext>, ControlTransformer<CodeBlockProps>>;
export type ControlTransformer<T = unknown> = ControlTransformer$1<Control, T>;
export type Extensions = StreamMarkdownExtensions<ComarkPlugin<any, any>, Component>;
export type HardenOptions = HardenOptions$1<Component>;
export type IconName = keyof typeof ICONS;
export type Icons = Icons$1<Component, IconName, OptionalIconName>;
export type ImageControlsConfig = ImageControlsConfig$1<ControlTransformer<MarkdownControlContext>>;
export type ImageOptions = ImageOptions$1<Component>;
export type MarkdownComponents = Record<string, Component>;
export type MermaidControlsConfig = MermaidControlsConfig$1<ControlTransformer<CodeBlockProps>>;
export type OptionalIconName = 'flipVertical' | 'rotateRight' | 'arrowRight';
export type PreviewerConfig = PreviewerConfig$1<Component>;
export type StreamMarkdownContext = StreamMarkdownContext$1<ControlsConfig, PreviewerConfig, HardenOptions, CodeOptions, ImageOptions, LinkOptions, UIOptions, Extensions>;
export type StreamMarkdownParserOptions<TPlugins extends readonly ComarkPlugin<any, any>[] = readonly ComarkPlugin<any, any>[]> = MarkmendParserOptions<TPlugins>;
export type StreamMarkdownProps = BaseStreamMarkdownProps & {
  completion?: Completion;
  literalTagContent?: string[];
  parserOptions?: StreamMarkdownParserOptions;
};
export type TableControlsConfig = TableControlsConfig$1<ControlTransformer<MarkdownControlContext>>;
export type TableOptions = TableOptions$1;
export type UIButtonProps = UIButtonProps$1<Component, CSSProperties>;
export type UIComponents = UIComponents$1<Component, BuiltinUIComponents$1>;
export type UIErrorComponentProps = UIErrorComponentProps$1<Component>;
export type UIIconProps = UIIconProps$1<Component, CSSProperties>;
export type UIImageProps = UIImageProps$1<unknown, ControlsConfig> & {
  sources?: string[];
};
export type UIModalProps = UIModalProps$1<CSSProperties>;
export type UISegmentedProps = UISegmentedProps$1<CSSProperties>;
export type UIZoomContainerProps = UIZoomContainerProps$1<CSSProperties>;
// #endregion

// #region Functions
export declare function isScrollAtBottom(_: ScrollMetrics, _?: number): boolean;
export declare function loadLocaleMessages(_: string | LocaleConfig$1): Promise<void>;
export declare function preloadAsyncComponents(_: Record<string, Component | undefined>, _?: string[], _?: string[]): Promise<void>;
export declare function provideMarkdownProvider(_: MarkdownProviderContext): void;
export declare function resolveExtensions(_: Extensions | undefined, _: ExtensionOverrides | undefined): Extensions | undefined;
export declare function resolveOwnedExtensions(_: Extensions | undefined, _: ExtensionOverrides | undefined): ExtensionRuntime[];
export declare function useCodeOptions(_: UseCodeOptionsOptions): {
  languageCodeOptions: import("vue").ComputedRef<import("@stream-markdown/core").CodeOptionsLanguage<import("vue").Component>>;
  showLanguageIcon: import("vue").ComputedRef<boolean>;
  showLanguageName: import("vue").ComputedRef<boolean>;
  showLineNumbers: import("vue").ComputedRef<boolean>;
};
export declare function useContext(): StreamMarkdownResolvedContext;
export declare function useControls(_: UseControlsOptions): {
  isControlEnabled: (_: string) => boolean;
  getControlValue: <T = any>(_: string) => T | undefined;
  resolveControls: <T>(_: string, _: Control[], _: T) => Control[];
};
export declare function useDarkDetector(_: MaybeRefOrGetter<boolean | undefined>, _: MaybeRefOrGetter<Record<string, string>>, _?: UseDarkDetectorOptions): {
  isDark: import("vue").ComputedRef<boolean>;
  isDarkProvided: import("vue").ComputedRef<boolean>;
  stop: () => void;
};
export declare function useDeferredRender(_: UseDeferredRenderOptions): {
  shouldRender: import("vue").Ref<boolean, boolean>;
};
export declare function useFloating(_: UseFloatingOptions): {
  referenceEl: import("vue").Ref<HTMLElement | undefined, HTMLElement | undefined>;
  floatingEl: import("vue").Ref<HTMLElement | undefined, HTMLElement | undefined>;
  open: import("vue").Ref<boolean, boolean>;
  appendTo: import("vue").Ref<string | Body | Element | undefined, string | Body | Element | undefined>;
  floatingStyle: import("vue").ComputedRef<{
    position: "absolute" | "fixed";
    top: string;
    left: string;
  }>;
  show: () => void;
  hide: () => void;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  onClick: () => void;
  onFloatingEnter: () => void;
  onFloatingLeave: () => void;
};
export declare function useI18n(): {
  t: (_: string, _?: string) => string;
};
export declare function useLinkFavicon(_: UseLinkFaviconOptions): {
  failed: import("vue").Ref<boolean, boolean>;
  handleError: () => void;
  handleLoad: () => void;
  loaded: import("vue").Ref<boolean, boolean>;
  show: import("vue").ComputedRef<boolean>;
  source: import("vue").Ref<string | undefined, string | undefined>;
};
export declare function useLocaleDetector(_: MaybeRefOrGetter<StreamMarkdownProps['locale']>): {
  locale: import("vue").ComputedRef<string | LocaleConfig$1>;
};
export declare function useMarkdownProvider(): MarkdownProviderContext | undefined;
export declare function useMathRenderer(_: UseMathRendererOptions): {
  html: import("vue").ComputedRef<string>;
  error: import("vue").ComputedRef<boolean>;
  errorMessage: import("vue").ComputedRef<string>;
};
export declare function useMediumZoom(_: UseMediumZoomOptions): {
  isAnimating: import("vue").Ref<boolean, boolean>;
  elementStyle: import("vue").ComputedRef<{
    opacity: number;
  }>;
  elementRef: import("vue").Ref<HTMLElement | undefined, HTMLElement | undefined>;
  zoomElementRef: import("vue").Ref<HTMLElement | undefined, HTMLElement | undefined>;
  zoomIn: () => Promise<void>;
  zoomOut: () => Promise<void>;
};
export declare function useMermaid(_?: UseMermaidOptions): {
  canRender: (_: string) => boolean;
  renderMermaid: (_: string) => Promise<import("@stream-markdown/core").MermaidExtensionRenderResult>;
  resolveExtension: (_: string) => import("@stream-markdown/core").MermaidExtension<import("vue").Component> | undefined;
  saveMermaid: (_: "svg" | "png", _: string, _?: (_: Error) => void, _?: string) => Promise<void>;
};
export declare function usePinnedScroll(_: UsePinnedScrollOptions): {
  pinned: import("vue").Ref<boolean, boolean>;
};
export declare function useSanitizers(_: UseSanitizersOptions): {
  hardenOptions: import("vue").ComputedRef<import("@stream-markdown/core").HardenOptions<unknown>>;
  transformHardenUrl: (_: string) => string | null;
  transformedUrl: import("vue").ComputedRef<string | null>;
  isHardenUrl: import("vue").ComputedRef<boolean>;
};
export declare function useTailwindV3Theme(_: UseTailwindV3ThemeOptions): {
  element: import("vue").ComputedRef<HTMLElement | undefined>;
  cssVariables: import("vue").Ref<Record<string, string>, Record<string, string>>;
  generateCSS: () => void;
  stop: () => void;
};
export declare function useZoom(_?: ZoomOptions): {
  zoom: import("vue").Ref<number, number>;
  translateX: import("vue").Ref<number, number>;
  translateY: import("vue").Ref<number, number>;
  isDragging: import("vue").Ref<boolean, boolean>;
  transformStyle: import("vue").ComputedRef<{
    transform: string;
  }>;
  zoomIn: () => void;
  zoomOut: () => void;
  resetZoom: () => void;
  setZoom: (_: number) => void;
  startDrag: (_: PointerEvent) => void;
  onDrag: (_: PointerEvent) => void;
  stopDrag: () => void;
  handleWheel: (_: WheelEvent, _: HTMLElement) => void;
  getState: () => ZoomState;
  setState: (_: Partial<ZoomState>) => void;
  handleTouchStart: (_: TouchEvent, _: HTMLElement) => void;
  handleTouchMove: (_: TouchEvent, _: HTMLElement) => void;
  handleTouchEnd: (_: TouchEvent) => void;
};
// #endregion

// #region Variables
export declare const CODE_PREVIEWERS: Partial<Record<string, Component>> & Record<BuiltinPreviewers$1, Component>;
export declare const currentLocale: import("vue").Ref<SupportedLanguage$1, SupportedLanguage$1>;
export declare const localeMessages: import("vue").Ref<LocaleConfig$1 | undefined, LocaleConfig$1 | undefined>;
export declare const Markdown: typeof __VLS_export$1;
export declare const MarkdownProvider: typeof __VLS_export;
export declare const UI: {
  readonly Alert: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<import("@stream-markdown/core").UIAlertProps & {
      open?: boolean;
    }> & Readonly<{
      onCancel?: (() => any) | undefined;
      onConfirm?: (() => any) | undefined;
      "onUpdate:open"?: ((value: boolean) => any) | undefined;
    }>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
      "update:open": (value: boolean) => any;
    } & {
      cancel: () => any;
      confirm: () => any;
    }, import("vue").PublicProps, {
      icon: string;
      zIndex: number;
    }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<import("@stream-markdown/core").UIAlertProps & {
      open?: boolean;
    }> & Readonly<{
      onCancel?: (() => any) | undefined;
      onConfirm?: (() => any) | undefined;
      "onUpdate:open"?: ((value: boolean) => any) | undefined;
    }>, {}, {}, {}, {}, {
      icon: string;
      zIndex: number;
    }>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<import("@stream-markdown/core").UIAlertProps & {
    open?: boolean;
  }> & Readonly<{
    onCancel?: (() => any) | undefined;
    onConfirm?: (() => any) | undefined;
    "onUpdate:open"?: ((value: boolean) => any) | undefined;
  }>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    "update:open": (value: boolean) => any;
  } & {
    cancel: () => any;
    confirm: () => any;
  }, string, {
    icon: string;
    zIndex: number;
  }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      default?: (props: {}) => any;
    } & {
      footer?: (props: {}) => any;
    };
  });
  readonly Button: import("vue").DefineComponent<UIButtonProps, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {} & {
    click: (event: MouseEvent, item?: import("@stream-markdown/core").SelectOption | undefined) => any;
  }, string, import("vue").PublicProps, Readonly<UIButtonProps> & Readonly<{
    onClick?: ((event: MouseEvent, item?: import("@stream-markdown/core").SelectOption | undefined) => any) | undefined;
  }>, {
    variant: "icon" | "text";
    buttonStyle: import("vue").CSSProperties;
    iconWidth: number;
    iconHeight: number;
    iconStyle: import("vue").CSSProperties;
    options: import("@stream-markdown/core").SelectOption[];
  }, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
  readonly Caret: import("vue").DefineComponent<{}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
  readonly CodeBlock: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<CodeBlockProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, import("vue").PublicProps, {}, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<CodeBlockProps> & Readonly<{}>, {}, {}, {}, {}, {}>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<CodeBlockProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, {}, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      title?: (props: {}) => any;
    } & {
      'header-center'?: (props: {}) => any;
    } & {
      actions?: (props: {}) => any;
    } & {
      default?: (props: {}) => any;
    };
  });
  readonly Dropdown: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<import("@stream-markdown/core").UIDropdownProps> & Readonly<{
      onClick?: ((event: MouseEvent, item: import("@stream-markdown/core").SelectOption) => any) | undefined;
    }>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {} & {
      click: (event: MouseEvent, item: import("@stream-markdown/core").SelectOption) => any;
    }, import("vue").PublicProps, {
      options: import("@stream-markdown/core").SelectOption[];
    }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<import("@stream-markdown/core").UIDropdownProps> & Readonly<{
      onClick?: ((event: MouseEvent, item: import("@stream-markdown/core").SelectOption) => any) | undefined;
    }>, {}, {}, {}, {}, {
      options: import("@stream-markdown/core").SelectOption[];
    }>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<import("@stream-markdown/core").UIDropdownProps> & Readonly<{
    onClick?: ((event: MouseEvent, item: import("@stream-markdown/core").SelectOption) => any) | undefined;
  }>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {} & {
    click: (event: MouseEvent, item: import("@stream-markdown/core").SelectOption) => any;
  }, string, {
    options: import("@stream-markdown/core").SelectOption[];
  }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      default?: (props: {}) => any;
    };
  });
  readonly ErrorComponent: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<UIErrorComponentProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, import("vue").PublicProps, {
      variant: import("@stream-markdown/core").UIErrorVariant;
      showIcon: boolean;
    }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<UIErrorComponentProps> & Readonly<{}>, {}, {}, {}, {}, {
      variant: import("@stream-markdown/core").UIErrorVariant;
      showIcon: boolean;
    }>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<UIErrorComponentProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, {
    variant: import("@stream-markdown/core").UIErrorVariant;
    showIcon: boolean;
  }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      default?: (props: {}) => any;
    };
  });
  readonly Icon: import("vue").DefineComponent<UIIconProps, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<UIIconProps> & Readonly<{}>, {
    width: number;
    height: number;
  }, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
  readonly Image: import("vue").DefineComponent<UIImageProps, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {} & {
    error: (event: Event) => any;
    load: (event: Event) => any;
  }, string, import("vue").PublicProps, Readonly<UIImageProps> & Readonly<{
    onError?: ((event: Event) => any) | undefined;
    onLoad?: ((event: Event) => any) | undefined;
  }>, {
    preview: boolean;
    margin: number;
  }, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
  readonly Modal: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<UIModalProps & {
      open?: boolean;
    }> & Readonly<{
      "onUpdate:open"?: ((value: boolean) => any) | undefined;
    }>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
      "update:open": (value: boolean) => any;
    }, import("vue").PublicProps, {
      zIndex: number;
      transition: string;
    }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<UIModalProps & {
      open?: boolean;
    }> & Readonly<{
      "onUpdate:open"?: ((value: boolean) => any) | undefined;
    }>, {}, {}, {}, {}, {
      zIndex: number;
      transition: string;
    }>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<UIModalProps & {
    open?: boolean;
  }> & Readonly<{
    "onUpdate:open"?: ((value: boolean) => any) | undefined;
  }>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    "update:open": (value: boolean) => any;
  }, string, {
    zIndex: number;
    transition: string;
  }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      title?: (props: {}) => any;
    } & {
      'header-center'?: (props: {}) => any;
    } & {
      actions?: (props: {}) => any;
    } & {
      default?: (props: {}) => any;
    };
  });
  readonly Segmented: import("vue").DefineComponent<UISegmentedProps & {
    value?: string;
  }, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    "update:value": (value: string) => any;
  } & {
    change: (value: string) => any;
  }, string, import("vue").PublicProps, Readonly<UISegmentedProps & {
    value?: string;
  }> & Readonly<{
    onChange?: ((value: string) => any) | undefined;
    "onUpdate:value"?: ((value: string) => any) | undefined;
  }>, {
    options: import("@stream-markdown/core").SelectOption[];
    buttonStyle: import("vue").CSSProperties;
  }, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
  readonly Spin: import("vue").DefineComponent<{}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
  readonly Table: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<import("@stream-markdown/core").UITableProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, import("vue").PublicProps, {}, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<import("@stream-markdown/core").UITableProps> & Readonly<{}>, {}, {}, {}, {}, {}>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<import("@stream-markdown/core").UITableProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, {}, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      'header-cell'?: (props: {
        cell: unknown;
        cellIndex: number;
      }) => any;
    } & {
      'body-cell'?: (props: {
        cell: unknown;
        rowIndex: number;
        cellIndex: number;
      }) => any;
    };
  });
  readonly Tooltip: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<import("@stream-markdown/core").UITooltipProps> & Readonly<{}>, {
      show: () => void;
      hide: () => void;
    }, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, import("vue").PublicProps, {
      trigger: "hover" | "click";
      placement: "top" | "bottom" | "left" | "right" | "top-start" | "top-end" | "bottom-start" | "bottom-end" | "left-start" | "left-end" | "right-start" | "right-end";
      delay: number | [number, number];
    }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<import("@stream-markdown/core").UITooltipProps> & Readonly<{}>, {
      show: () => void;
      hide: () => void;
    }, {}, {}, {}, {
      trigger: "hover" | "click";
      placement: "top" | "bottom" | "left" | "right" | "top-start" | "top-end" | "bottom-start" | "bottom-end" | "left-start" | "left-end" | "right-start" | "right-end";
      delay: number | [number, number];
    }>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<import("@stream-markdown/core").UITooltipProps> & Readonly<{}>, {
    show: () => void;
    hide: () => void;
  }, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, {
    trigger: "hover" | "click";
    placement: "top" | "bottom" | "left" | "right" | "top-start" | "top-end" | "bottom-start" | "bottom-end" | "left-start" | "left-end" | "right-start" | "right-end";
    delay: number | [number, number];
  }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      default?: (props: {}) => any;
    } & {
      content?: (props: {}) => any;
    };
  });
  readonly ZoomContainer: {
    new (...args: any[]): import("vue").CreateComponentPublicInstanceWithMixins<Readonly<UIZoomContainerProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, import("vue").PublicProps, {
      interactive: boolean;
      showControl: boolean;
      controlSize: "vanilla" | "large";
      position: import("@stream-markdown/core").ZoomControlPosition;
      containerStyle: import("vue").CSSProperties;
    }, false, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
      P: {};
      B: {};
      D: {};
      C: {};
      M: {};
      Defaults: {};
    }, Readonly<UIZoomContainerProps> & Readonly<{}>, {}, {}, {}, {}, {
      interactive: boolean;
      showControl: boolean;
      controlSize: "vanilla" | "large";
      position: import("@stream-markdown/core").ZoomControlPosition;
      containerStyle: import("vue").CSSProperties;
    }>;
    __isFragment?: never;
    __isTeleport?: never;
    __isSuspense?: never;
  } & import("vue").ComponentOptionsBase<Readonly<UIZoomContainerProps> & Readonly<{}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, {
    interactive: boolean;
    showControl: boolean;
    controlSize: "vanilla" | "large";
    position: import("@stream-markdown/core").ZoomControlPosition;
    containerStyle: import("vue").CSSProperties;
  }, {}, string, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, import("vue").ComponentProvideOptions> & import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps & (new () => {
    $slots: {
      controls?: (props: {
        iconWidth?: undefined;
        iconHeight?: undefined;
        buttonStyle?: undefined;
      } | {
        iconWidth: number;
        iconHeight: number;
        buttonStyle: {
          fontSize: string;
        };
      }) => any;
    } & {
      default?: (props: {}) => any;
    };
  });
};
// #endregion

// #region Re-exports
export * from "@markmend/parser";
// #endregion

// #region Referenced (internal)
type BaseStreamMarkdownProps = StreamMarkdownProps$1<MarkdownComponents, Icons, UIComponents, CaretType$1, ControlsConfig, PreviewerConfig, HardenOptions, CodeOptions, ImageOptions, LinkOptions, UIOptions, ExtensionOverrides>;
interface ScrollMetrics {
  clientHeight: number;
  scrollHeight: number;
  scrollTop: number;
}
interface UseCodeOptionsOptions {
  codeOptions?: MaybeRefOrGetter<CodeOptions | undefined>;
  language?: MaybeRefOrGetter<string>;
}
interface UseControlsOptions {
  controls: MaybeRefOrGetter<ControlsConfig | undefined>;
}
interface UseDarkDetectorOptions {
  manageOverlay?: MaybeRefOrGetter<boolean>;
}
interface UseDeferredRenderOptions {
  targetRef: MaybeRefOrGetter<HTMLElement | null | undefined>;
  immediate?: boolean;
  debounceDelay?: number;
  rootMargin?: string;
  idleTimeout?: number;
}
interface UseFloatingOptions {
  hideTooltip?: MaybeRefOrGetter<boolean>;
  trigger?: MaybeRefOrGetter<'hover' | 'click'>;
  placement?: MaybeRefOrGetter<Placement>;
  delay?: MaybeRefOrGetter<number | [number, number]>;
  getContainer?: () => Element | HTMLElement | undefined | null;
}
interface UseLinkFaviconOptions {
  enabled: MaybeRefOrGetter<boolean>;
  favicon: MaybeRefOrGetter<LinkOptions['favicon']>;
  loading: MaybeRefOrGetter<boolean | undefined>;
  url: MaybeRefOrGetter<string | null | undefined>;
  waitingForDestination: MaybeRefOrGetter<boolean | undefined>;
}
interface UseMathRendererOptions {
  node: MaybeRefOrGetter<MathRenderNode>;
  extension?: MaybeRefOrGetter<Extensions['math'] | undefined>;
  throttle?: MaybeRefOrGetter<number>;
}
interface UseMediumZoomOptions {
  margin?: MaybeRefOrGetter<number>;
  open?: () => void;
  close?: () => void;
}
interface UseMermaidOptions {
  extensions?: MaybeRefOrGetter<Extensions | undefined>;
  isDark?: MaybeRefOrGetter<boolean>;
}
interface UsePinnedScrollOptions {
  target: MaybeRefOrGetter<HTMLElement | undefined>;
  active: MaybeRefOrGetter<boolean>;
  enabled: MaybeRefOrGetter<boolean>;
  contentKey?: MaybeRefOrGetter<unknown>;
}
interface UseSanitizersOptions {
  url?: MaybeRefOrGetter<string | undefined>;
  hardenOptions?: MaybeRefOrGetter<HardenOptions | undefined>;
  loading?: MaybeRefOrGetter<boolean | undefined>;
  isImage?: MaybeRefOrGetter<boolean | undefined>;
}
interface UseTailwindV3ThemeOptions {
  element?: () => HTMLElement | undefined;
  enabled?: MaybeRefOrGetter<boolean>;
}
// #endregion

// #region Other
export { ANIMATION_SPLITS }
export { ANIMATION_TYPES }
export { AnimationSplit }
export { AnimationType }
export { BuiltinPreviewers }
export { BuiltinUIComponents }
export { CARETS }
export { CaretType }
export { CdnModule }
export { CdnOptions }
export { ComarkPlugin }
export { Completion }
export { CompletionFunction }
export { CSVSeparator }
export { DEFAULT_ANIMATION }
export { DEFAULT_ANIMATION_SPLIT }
export { DEFAULT_HARDEN_OPTIONS }
export { DEFAULT_LANGUAGE }
export { DownloadControlConfig }
export { DownloadControlOptions }
export { DownloadEvent }
export { LinkOptions }
export { LocaleConfig }
export { MarkdownDocument }
export { ElementNode as MarkdownElement }
export { MaybeArray }
export { MaybePromise }
export { PreviewSegmentedPlacement }
export { SelectOption }
export { SHADCN_SCHEMAS }
export { StreamMarkdownHooks }
export { SUPPORT_LANGUAGES }
export { SupportedLanguage }
export { UIAlertProps }
export { UIDropdownProps }
export { UIErrorVariant }
export { UIOptions }
export { UITableProps }
export { UITooltipProps }
export { ZoomControlPosition }
// #endregion