/**
 * Generated by tsnapi — public API snapshot of `@stream-markdown/core`
 */
// #region Interfaces
export interface AnimationSchedule {
  baseDelay: number;
  step: number;
}
export interface AnimationTimeline {
  beginPass: (_?: number) => number;
  commitPass: () => void;
  reset: () => void;
  take: (_: number, _: number, _: number) => AnimationSchedule;
}
export interface BrowserTouchZoomInput {
  event: TouchEvent;
  element: Element;
  state: ZoomState;
}
export interface BrowserTouchZoomMoveInput {
  event: TouchEvent;
  element: Element;
  touchState: TouchZoomState;
  options?: ZoomOptions;
}
export interface BrowserWheelZoomInput {
  event: WheelEvent;
  element: Element;
  state: ZoomState;
  options?: ZoomOptions;
}
export interface CdnOptions {
  baseUrl?: string;
  getUrl?: (_: CdnModule, _: string) => string | undefined;
  shiki?: boolean;
  mermaid?: ModuleStrategy | false;
  beautifulMermaid?: ModuleStrategy | false;
  katex?: ModuleStrategy | false;
}
export interface CodeBlockControlActionOptions {
  key: string;
  select?: SelectOption;
  filename?: string;
  state: CodeBlockControlState;
  node: CodeBlockNode;
  language: string;
  beforeDownload?: (_: DownloadEvent) => MaybePromise<boolean>;
  copyText?: (_: string) => MaybePromise<void>;
  onCopied?: (_: string) => void;
  saveFile?: (_: string, _: string | Blob, _: string) => MaybePromise<void>;
  saveMermaid?: (_: 'svg' | 'png', _: string, _?: string) => MaybePromise<void>;
}
export interface CodeBlockControlDescriptorOptions {
  collapsed: boolean;
  fullscreen: boolean;
  copied: boolean;
  language: string;
  showCollapse: boolean;
  showCopy: boolean;
  showDownload: boolean;
  showFullscreen: boolean;
  downloadOptions?: SelectOption[];
}
export interface CodeBlockControlState {
  collapsed: boolean;
  fullscreen: boolean;
}
export interface CodeBlockModel<TComponent = unknown> extends CodeOptionsModel<TComponent> {
  language: string;
  progressiveRender: boolean;
  previewPlacement: PreviewSegmentedPlacement;
  previewable: boolean;
  inlineInteractive: boolean;
  maxHeight?: string;
  downloadOptions: SelectOption[];
}
export interface CodeBlockModelOptions<TComponent = unknown> {
  node: CodeBlockNode;
  codeOptions?: CodeOptions<TComponent>;
  previewers?: PreviewerConfig<TComponent>;
  controls?: unknown;
  hasMermaid?: boolean;
  mode: 'preview' | 'source';
  isPreviewComponent?: (_: unknown) => boolean;
}
export interface CodeBlockModeState {
  mode: 'preview' | 'source';
}
export interface CodeBlockNode {
  value: string;
  lang?: string | null;
  meta?: string;
  loading?: boolean;
}
export interface CodeExtension extends ExtensionRuntime {
  highlight: (_: CodeHighlightInput) => Promise<CodeHighlightResult>;
  getTheme?: (_: boolean) => Promise<Record<string, unknown> | null>;
}
export interface CodeHighlightInput {
  code: string;
  isDark: boolean;
  language: string;
}
export interface CodeHighlightResult {
  bg?: string;
  fg?: string;
  grammarState?: {
    lang?: string;
  };
  themeName?: string;
  tokens: CodeToken[][];
}
export interface CodeMaxHeightOptions<TComponent = unknown> {
  mode: 'preview' | 'source';
  codeOptions?: CodeOptions<TComponent>;
  language: string;
}
export interface CodeOptions<TComponent = unknown> {
  languageIcon?: boolean;
  languageName?: boolean;
  lineNumbers?: boolean;
  maxHeight?: number | string;
  language?: Record<string, CodeOptionsLanguage<TComponent>>;
}
export interface CodeOptionsLanguage<TComponent = unknown> extends Omit<CodeOptions<TComponent>, 'languageIcon'> {
  languageIcon?: boolean | TComponent;
}
export interface CodeOptionsModel<TComponent = unknown> {
  languageCodeOptions: CodeOptionsLanguage<TComponent>;
  showLanguageIcon: boolean;
  showLanguageName: boolean;
  showLineNumbers: boolean;
  showLanguageTitle: boolean;
}
export interface CodePreviewableOptions<TComponent = unknown> {
  previewers?: PreviewerConfig<TComponent>;
  language: string;
  nodeLoading?: boolean;
  hasMermaid?: boolean;
  progressiveRender?: boolean;
  isPreviewComponent?: (_: unknown) => boolean;
}
export interface CodeToken {
  content: string;
  htmlStyle?: Record<string, string | number | undefined>;
}
export interface ContentDownloadEvent {
  type: 'code' | 'mermaid' | 'table';
  content: string;
}
export interface ControlDescriptor<TStyle = UIStyleValue> {
  key: string;
  labelKey?: string;
  label?: string;
  icon?: string;
  variant?: 'icon' | 'text';
  options?: SelectOption[];
  visible?: boolean;
  buttonStyle?: TStyle;
  iconStyle?: TStyle;
  iconWidth?: number;
  iconHeight?: number;
}
export interface CreateAnimationTimelineOptions {
  maxBacklog?: number;
  minStagger?: number;
  now?: () => number;
}
export interface DownloadControlOptions {
  filename: string;
}
export interface ErrorModelOptions {
  variant?: UIErrorVariant;
  message?: string;
  icon?: unknown;
  hasIcon?: (_: string) => boolean;
}
export interface ExtensionRuntime {
  preload: () => MaybePromise<void>;
  dispose: () => MaybePromise<void>;
}
export interface FloatingPositionState {
  x?: number | null;
  y?: number | null;
  strategy?: 'absolute' | 'fixed';
}
export interface HardenOptions<TComponent = unknown> {
  defaultOrigin?: string;
  allowedLinkPrefixes?: string[];
  allowedImagePrefixes?: string[];
  allowedProtocols?: string[];
  allowDataImages?: boolean;
  errorComponent?: TComponent;
}
export interface HtmlPreviewerOptions {
  autoHeight?: boolean;
  height?: number | string;
  maxHeight?: number | string;
  sandbox?: string;
}
export interface ImageModelOptions<TComponent = unknown> {
  node: ImageRenderNode;
  imageOptions?: ImageOptions<TComponent>;
  fallbackAttempted?: boolean;
  imageLoaded?: boolean;
  isHardenUrl?: boolean;
  loadError?: boolean;
}
export interface ImageOptions<TComponent = unknown> {
  fallback?: string;
  caption?: boolean;
  referrerPolicy?: ReferrerPolicy;
  errorComponent?: TComponent;
}
export interface ImagePreviewControlDescriptor extends ControlDescriptor {
  key: ImagePreviewControlKey;
}
export interface ImagePreviewIconAvailability {
  arrowRight?: boolean;
  flipVertical?: boolean;
  rotateRight?: boolean;
}
export interface ImagePreviewModelOptions {
  sources?: string[];
  src?: string;
  controls?: unknown;
  transformHardenUrl?: (_: string) => string | null;
  hasDownload?: boolean;
  preview?: boolean;
  loaded?: boolean;
  hasElement?: boolean;
  state?: Partial<ImagePreviewTransformState>;
  icons?: ImagePreviewIconAvailability;
  elementStyle?: UIStyleValue;
}
export interface ImagePreviewTransformState {
  scaleX: number;
  scaleY: number;
  rotate: number;
}
export interface ImageRenderNode {
  url: string;
  alt?: string | null;
  title?: string | null;
  loading?: boolean;
}
export interface LinkOptions {
  favicon?: boolean | LinkFaviconResolver;
  safetyCheck?: boolean;
  isTrusted?: (_: string) => Promise<boolean> | boolean;
}
export interface LocaleConfig {
  button: {
    zoomIn: string;
    zoomOut: string;
    resetZoom: string;
    preview: string;
    source: string;
    collapse: string;
    copy: string;
    copied: string;
    download: string;
    minimize: string;
    maximize: string;
    flipY: string;
    flipX: string;
    rotateLeft: string;
    rotateRight: string;
    previous: string;
    next: string;
    back: string;
    confirm: string;
    cancel: string;
  };
  error: {
    vanilla: string;
    image: string;
    mermaid: string;
    katex: string;
    harden: string;
  };
  link: {
    title: string;
    description: string;
    copy: string;
    open: string;
  };
  dialog?: {
    fullscreen: string;
    imagePreview: string;
  };
}
export interface MathExtension<TParserPlugin = unknown, TErrorComponent = unknown> extends ExtensionRuntime {
  ensureCss?: () => MaybePromise<void>;
  errorComponent?: TErrorComponent;
  parserPlugin: TParserPlugin;
  render: (_: MathRenderInput) => Promise<MathRenderResult>;
}
export interface MathRendererModelOptions {
  node: MathRenderNode;
  installed: boolean;
  renderFlag?: boolean;
  renderingCode?: string;
  errorMessage?: string;
}
export interface MathRendererResult {
  html?: string;
  error?: string;
}
export interface MathRendererState {
  html: string;
  errorMessage: string;
  renderFlag: boolean;
  renderingCode: string;
}
export interface MathRenderInput {
  code: string;
  displayMode: boolean;
}
export interface MathRenderNode {
  value: string;
  display: boolean;
  loading?: boolean;
}
export interface MathRenderResult {
  error?: string;
  html?: string;
}
export interface MediumZoomOutTransformInput {
  originalRect: ZoomRect;
  zoomRect: ZoomRect;
  currentTransform: string;
}
export interface MediumZoomTransformInput {
  rect: ZoomRect;
  naturalWidth: number;
  naturalHeight: number;
  viewportWidth: number;
  viewportHeight: number;
  margin: number;
}
export interface MediumZoomTransformResult {
  initialTransform: string;
  targetTransform: string;
}
export interface MermaidExtension<TErrorComponent = unknown> extends ExtensionRuntime {
  errorComponent?: TErrorComponent;
  render: (_: MermaidRenderInput) => Promise<MermaidExtensionRenderResult>;
  supports: (_: string) => boolean;
}
export interface MermaidExtensionRenderResult {
  error?: string;
  supported?: boolean;
  svg?: string;
  valid: boolean;
}
export interface MermaidPreviewControllerState extends MermaidRenderState {
  svg?: string;
  error?: string;
  measuredHeight: number;
}
export interface MermaidPreviewModelOptions {
  code: string;
  nodeLoading?: boolean;
  svg?: string;
  renderFlag?: boolean;
  minHeight?: number;
  containerHeight?: number | string;
  measuredHeight?: number;
  controls?: unknown;
}
export interface MermaidRenderInput {
  code: string;
  isDark: boolean;
  theme?: Record<string, unknown> | null;
}
export interface MermaidRenderResult {
  valid: boolean;
  svg?: string;
  error?: string;
}
export interface MermaidRenderState {
  renderFlag: boolean;
  renderAttempt: boolean;
}
export interface SelectOption {
  label: string;
  value: string | number;
  icon?: string;
}
export interface StreamMarkdownContext<TControls = unknown, TPreviewers = unknown, THardenOptions = unknown, TCodeOptions = unknown, TImageOptions = unknown, TLinkOptions = unknown, TUIOptions = unknown, TExtensions = unknown> {
  controls?: TControls;
  previewers?: TPreviewers;
  hardenOptions?: THardenOptions;
  codeOptions?: TCodeOptions;
  tableOptions?: TableOptions;
  imageOptions?: TImageOptions;
  linkOptions?: TLinkOptions;
  uiOptions?: TUIOptions;
  extensions?: TExtensions;
  isDark?: boolean;
}
export interface StreamMarkdownExtensions<TParserPlugin = unknown, TComponent = unknown> {
  beautifulMermaid?: MermaidExtension<TComponent>;
  code?: CodeExtension;
  math?: MathExtension<TParserPlugin, TComponent>;
  mermaid?: MermaidExtension<TComponent>;
}
export interface StreamMarkdownHooks {
  beforeDownload?: (_: DownloadEvent) => MaybePromise<boolean>;
}
export interface StreamMarkdownViewProps<TMarkdownComponents = unknown, TIcons = unknown, TUIComponents = unknown, TCaret extends string = string> {
  mode?: 'static' | 'streaming';
  dir?: TextDirectionConfig;
  content?: string;
  components?: TMarkdownComponents;
  icons?: Partial<TIcons>;
  uiComponents?: Partial<TUIComponents>;
  locale?: string | LocaleConfig;
  enableAnimate?: boolean;
  animation?: AnimationType;
  animationSplit?: AnimationSplit;
  animationDuration?: number | string;
  animationStagger?: number;
  caret?: TCaret;
  themeElement?: () => HTMLElement | undefined;
}
export interface SvgIntrinsicSize {
  width: number;
  height: number;
}
export interface TableContent {
  content: string;
  mimeType: string;
  extension: string;
}
export interface TableControlActionOptions {
  key: string;
  select?: SelectOption;
  filename?: string;
  state: TableControlState;
  getContent: (_: TableFormat) => TableContent | null;
  beforeDownload?: (_: DownloadEvent) => MaybePromise<boolean>;
  copyContent?: (_: string) => MaybePromise<void>;
  onCopied?: (_: string) => void;
  saveFile?: (_: string, _: string | Blob, _: string) => MaybePromise<void>;
}
export interface TableControlDescriptorOptions {
  copied: boolean;
  fullscreen: boolean;
  showCopy: boolean;
  showDownload: boolean;
  showFullscreen: boolean;
  options?: SelectOption[];
}
export interface TableControlState {
  fullscreen: boolean;
}
export interface TableData {
  headers: string[];
  rows: string[][];
}
export interface TableOptions {
  maxHeight?: number | string;
}
export interface TextAnimationPassOptions {
  enabled: boolean;
  stagger: number;
}
export interface TextAnimationScheduler {
  beginPass: (_: TextAnimationPassOptions) => void;
  commitPass: () => void;
  schedule: (_: TextPart[]) => ReadonlyMap<string, number>;
}
export interface TextPart {
  key: string;
  value: string;
  whitespace: boolean;
  animationSplit: ResolvedAnimationSplit;
}
export interface TouchZoomInput {
  state: ZoomState;
  rect: ZoomRect;
  touches: [ZoomPoint, ZoomPoint];
  options?: ZoomOptions;
}
export interface TouchZoomMoveInput {
  rect: ZoomRect;
  touches: [ZoomPoint, ZoomPoint];
  touchState: TouchZoomState;
  options?: ZoomOptions;
}
export interface TouchZoomState {
  initialDistance: number;
  initialZoom: number;
  initialTranslateX: number;
  initialTranslateY: number;
  centerX: number;
  centerY: number;
}
export interface UIAlertProps {
  icon?: string;
  title?: string;
  description?: string;
  zIndex?: number;
  confirmText?: string;
  cancelText?: string;
  open?: boolean;
}
export interface UIButtonProps<TComponent = unknown, TStyle = UIStyleValue, TClass = UIClassValue> {
  variant?: 'icon' | 'text';
  name: string;
  buttonClass?: TClass;
  buttonStyle?: TStyle;
  icon?: string | TComponent;
  iconWidth?: number;
  iconHeight?: number;
  iconClass?: TClass;
  iconStyle?: TStyle;
  options?: SelectOption[];
  announcement?: string;
}
export interface UIDropdownProps {
  title?: string;
  options?: SelectOption[];
}
export interface UIErrorComponentProps<TComponent = unknown> {
  variant?: UIErrorVariant;
  showIcon?: boolean;
  icon?: string | TComponent;
  message?: string;
}
export interface UIIconProps<TComponent = unknown, TStyle = UIStyleValue, TClass = UIClassValue> {
  icon: string | TComponent;
  width?: number;
  height?: number;
  class?: TClass;
  style?: TStyle;
}
export interface UIImageProps<TNodeProps = unknown, TControls = unknown> {
  src?: string;
  alt?: string;
  title?: string;
  preview?: boolean;
  referrerPolicy?: ReferrerPolicy;
  margin?: number;
  controls?: TControls;
  transformHardenUrl?: (_: string) => string | null;
  nodeProps: TNodeProps;
  handleDownload?: (_: string) => Promise<void>;
}
export interface UIModalProps<TStyle = UIStyleValue> {
  title?: string;
  titleId?: string;
  ariaLabel?: string;
  zIndex?: number;
  modalStyle?: TStyle;
  headerStyle?: TStyle;
  transition?: string;
  close?: () => void;
  open?: boolean;
}
export interface UIOptions {
  hideTooltip?: boolean;
}
export interface UISegmentedProps<TStyle = UIStyleValue> {
  options?: SelectOption[];
  buttonStyle?: TStyle;
  value?: string;
}
export interface UITableProps {
  getAlign?: (_: number) => 'left' | 'center' | 'right';
  getDirection?: (_: unknown) => TextDirection | undefined;
  headers?: unknown[];
  rows?: Array<{
    children: unknown[];
  }>;
}
export interface UITooltipProps {
  content?: string;
  trigger?: 'hover' | 'click';
  placement?: 'top' | 'bottom' | 'left' | 'right' | 'top-start' | 'top-end' | 'bottom-start' | 'bottom-end' | 'left-start' | 'left-end' | 'right-start' | 'right-end';
  delay?: number | [number, number];
}
export interface UIZoomContainerProps<TStyle = UIStyleValue> {
  interactive?: boolean;
  showControl?: boolean;
  controlSize?: 'vanilla' | 'large';
  position?: ZoomControlPosition;
  containerStyle?: TStyle;
}
export interface UrlDownloadEvent {
  type: 'image';
  url: string;
}
export interface WheelZoomInput {
  state: ZoomState;
  point: ZoomPoint;
  rect: ZoomRect;
  deltaY: number;
  ctrlKey?: boolean;
  metaKey?: boolean;
  options?: ZoomOptions;
}
export interface ZoomControlPositionStyle {
  top?: string;
  right?: string;
  bottom?: string;
  left?: string;
  transform?: string;
}
export interface ZoomOptions {
  minZoom?: number;
  maxZoom?: number;
  zoomStep?: number;
  wheelSensitivity?: number;
  initialZoom?: number;
  initialTranslateX?: number;
  initialTranslateY?: number;
}
export interface ZoomPoint {
  x: number;
  y: number;
}
export interface ZoomRect {
  left: number;
  top: number;
  width: number;
  height: number;
}
export interface ZoomState {
  zoom: number;
  translateX: number;
  translateY: number;
}
// #endregion

// #region Types
export type AnimationSplit = typeof ANIMATION_SPLITS[number];
export type AnimationType = typeof ANIMATION_TYPES[number] | (string & {});
export type BuiltinPreviewers = 'mermaid' | 'html';
export type BuiltinUIComponents = 'Alert' | 'Button' | 'Caret' | 'CodeBlock' | 'Dropdown' | 'ErrorComponent' | 'Icon' | 'Image' | 'Modal' | 'Segmented' | 'Spin' | 'Table' | 'Tooltip' | 'ZoomContainer';
export type CaretType = 'block' | 'circle';
export type CdnModule = 'shiki' | 'mermaid' | 'beautiful-mermaid' | 'katex' | 'katex-css';
export type CodeControlsConfig<TTransformer = unknown> = boolean | {
  collapse?: boolean;
  copy?: boolean;
  download?: DownloadControlConfig;
  fullscreen?: boolean;
  customize?: TTransformer;
};
export type Control<TButtonProps extends object = UIButtonProps, TEvent = MouseEvent> = TButtonProps & {
  key: string;
  visible?: () => boolean;
  onClick: (_: TEvent, _?: SelectOption) => void;
};
export type ControlsConfig<TTableTransformer = unknown, TCodeTransformer = unknown, TImageTransformer = unknown, TMermaidTransformer = unknown> = boolean | {
  table?: boolean | TableControlsConfig<TTableTransformer>;
  code?: boolean | CodeControlsConfig<TCodeTransformer>;
  image?: boolean | ImageControlsConfig<TImageTransformer>;
  mermaid?: boolean | MermaidControlsConfig<TMermaidTransformer>;
};
export type ControlTransformer<TControl, TProps> = (_: TControl[], _: TProps) => TControl[];
export type CSVSeparator = ',' | ';' | '\t' | 'auto';
export type DownloadControlConfig = boolean | DownloadControlOptions;
export type DownloadEvent = UrlDownloadEvent | ContentDownloadEvent;
export type FloatingDelay = number | [number, number];
export type HtmlPreviewMeasurementMode = 'dom' | 'message' | 'fallback';
export type Icons<TComponent = unknown, TIconName extends PropertyKey = string, TOptionalIconName extends PropertyKey = never> = Record<TIconName, TComponent> & Partial<Record<TOptionalIconName, TComponent>> & Record<string, TComponent>;
export type IdleCallbackId = number | ReturnType<typeof globalThis.setTimeout>;
export type ImageControlsConfig<TTransformer = unknown> = boolean | {
  preview?: boolean;
  download?: boolean;
  carousel?: boolean;
  flip?: boolean;
  rotate?: boolean;
  controlPosition?: ZoomControlPosition;
  customize?: TTransformer;
};
export type ImagePreviewControlKey = 'download' | 'previous' | 'next' | 'flipX' | 'flipY' | 'rotateLeft' | 'rotateRight';
export type LinkFaviconResolver = (_: string) => MaybePromise<string | undefined>;
export type MaybeArray<T> = T | T[];
export type MaybeGetter<T> = T | (() => T);
export type MaybePromise<T> = T | Promise<T>;
export type MermaidControlsConfig<TTransformer = unknown> = boolean | {
  download?: DownloadControlConfig;
  inlineInteractive?: boolean;
  position?: ZoomControlPosition;
  customize?: TTransformer;
};
export type ModuleStrategy = 'esm' | 'umd';
export type PreviewerConfig<TComponent = unknown> = boolean | {
  placement?: PreviewSegmentedPlacement;
  progressive?: Record<string, boolean>;
  html?: HtmlPreviewerOptions;
  components?: {
    mermaid?: boolean | TComponent;
    html?: boolean | TComponent;
  } & Record<string, TComponent>;
};
export type PreviewSegmentedPlacement = 'left' | 'center' | 'right' | 'auto';
export type ResolvedAnimationSplit = Exclude<AnimationSplit, 'auto'>;
export type SharedCdnModule = CdnModule;
export type SharedCdnOptions = CdnOptions;
export type StreamMarkdownMode = 'static' | 'streaming';
export type StreamMarkdownProps<TMarkdownComponents = unknown, TIcons = unknown, TUIComponents = unknown, TCaret extends string = string, TControls = unknown, TPreviewers = unknown, THardenOptions = unknown, TCodeOptions = unknown, TImageOptions = unknown, TLinkOptions = unknown, TUIOptions = unknown, TExtensions = unknown> = StreamMarkdownContext<TControls, TPreviewers, THardenOptions, TCodeOptions, TImageOptions, TLinkOptions, TUIOptions, TExtensions> & StreamMarkdownViewProps<TMarkdownComponents, TIcons, TUIComponents, TCaret> & StreamMarkdownHooks;
export type SupportedLanguage = 'en-US' | 'zh-CN';
export type TableAlign = 'left' | 'center' | 'right';
export type TableControlsConfig<TTransformer = unknown> = boolean | {
  copy?: boolean | string;
  csvSeparator?: CSVSeparator;
  download?: DownloadControlConfig | string;
  fullscreen?: boolean;
  customize?: TTransformer;
};
export type TableFormat = 'csv' | 'tsv' | 'markdown';
export type TextDirection = 'ltr' | 'rtl';
export type TextDirectionConfig = 'auto' | TextDirection;
export type UIClassValue = string | string[] | Record<string, unknown>;
export type UIComponents<TComponent = unknown, TComponentName extends PropertyKey = string> = Record<TComponentName, TComponent>;
export type UIErrorVariant = 'vanilla' | 'image' | 'mermaid' | 'katex' | 'harden-image' | 'harden-link';
export type UIStyleValue = Record<string, string | number | undefined>;
export type ZoomControlPosition = 'top-left' | 'top-right' | 'top-center' | 'bottom-left' | 'bottom-right' | 'bottom-center';
// #endregion

// #region Functions
export declare function applyMathRendererResult(_: MathRendererState, _: string, _: MathRendererResult): MathRendererState;
export declare function applyMermaidRenderResult(_: MermaidPreviewControllerState, _: MermaidRenderResult): MermaidPreviewControllerState;
export declare function calculateMediumZoomInTransforms(_: {
  original: HTMLElement;
  cloned: HTMLElement;
  margin: number;
}): ReturnType<typeof calculateMediumZoomTransforms>;
export declare function calculateMediumZoomOutTransform({ originalRect, zoomRect, currentTransform }: MediumZoomOutTransformInput): string;
export declare function calculateMediumZoomTransforms({ rect, naturalWidth, naturalHeight, viewportWidth, viewportHeight, margin }: MediumZoomTransformInput): MediumZoomTransformResult;
export declare function calculateSvgContainerHeight(_: SvgIntrinsicSize, _: number): number;
export declare function capturePointerForNonMouseEvent(_: PointerEvent): boolean;
export declare function clampHtmlPreviewHeight(_: number, _?: number): number;
export declare function clampZoom(_: number, _: number, _: number): number;
export declare function cloneMediumZoomElement(_: HTMLElement): HTMLElement;
export declare function createAnimationTimeline(_?: CreateAnimationTimelineOptions): AnimationTimeline;
export declare function createBrowserTouchMovedState({ event, element, touchState, options }: BrowserTouchZoomMoveInput): ZoomState | null;
export declare function createBrowserTouchZoomState({ event, element, state }: BrowserTouchZoomInput): TouchZoomState | null;
export declare function createBrowserWheelZoomState({ event, element, state, options }: BrowserWheelZoomInput): ZoomState | null;
export declare function createCodeBlockControlDescriptors(_: CodeBlockControlDescriptorOptions): ControlDescriptor[];
export declare function createCodeBlockModel<TComponent = unknown>(_: CodeBlockModelOptions<TComponent>): CodeBlockModel<TComponent>;
export declare function createCodeOptionsModel<TComponent = unknown>(_: CodeOptions<TComponent> | undefined, _: string): CodeOptionsModel<TComponent>;
export declare function createCodeRendererModel(_: CodeBlockNode): {
  code: string;
  lang: string;
  languageClass: string;
  lines: string[];
  noLineNumbers: boolean;
  startLine: number;
};
export declare function createDraggedState(_: ZoomPoint, _: ZoomPoint): Pick<ZoomState, 'translateX' | 'translateY'>;
export declare function createDragStart(_: ZoomPoint, _: ZoomState): ZoomPoint;
export declare function createErrorModel(_?: ErrorModelOptions): {
  variant: UIErrorVariant;
  icon: {};
  messageKey: string;
  message: string | undefined;
  isHarden: boolean;
};
export declare function createFloatingStyle(_: FloatingPositionState): {
  position: "absolute" | "fixed";
  top: string;
  left: string;
};
export declare function createHtmlPreviewModel(_: CodeBlockNode): {
  code: string;
};
export declare function createHtmlPreviewSrcdoc(_: string): string;
export declare function createIconModel(_: {
  width?: number;
  height?: number;
}): {
  width: number;
  height: number;
  style: {
    width: string;
    height: string;
  };
};
export declare function createIdleCallback(): {
  request: (_: IdleRequestCallback, _?: number) => IdleCallbackId;
  cancel: (_: IdleCallbackId) => void;
};
export declare function createImageModel<TComponent = unknown>(_: ImageModelOptions<TComponent>): {
  readonly isLoading: boolean;
  readonly fallback: string;
  readonly imageSrc: string;
  readonly alt: string;
  readonly title: string;
  readonly showCaption: boolean;
  readonly figureWidth: "100%" | "auto";
  readonly showSpin: boolean;
  readonly showImage: boolean;
  readonly showError: boolean;
  readonly errorVariant: "harden-image" | "image";
};
export declare function createImagePreviewControlDescriptors(_: Pick<ImagePreviewModelOptions, 'controls' | 'hasDownload' | 'icons'> & {
  imageCount?: number;
  imageSrc?: string;
}): ImagePreviewControlDescriptor[];
export declare function createImagePreviewModel(_: ImagePreviewModelOptions): {
  sources: string[];
  controlPosition: ZoomControlPosition;
  canOpen: boolean;
  transformState: ImagePreviewTransformState;
  imageStyle: UIStyleValue;
  controls: ImagePreviewControlDescriptor[];
};
export declare function createImagePreviewSources(_?: string[], _?: (_: string) => string | null): string[];
export declare function createImagePreviewTransformState(_?: Partial<ImagePreviewTransformState>): ImagePreviewTransformState;
export declare function createImagePreviewTransformStyle(_?: Partial<ImagePreviewTransformState>, _?: UIStyleValue): UIStyleValue;
export declare function createMathRendererModel(_: MathRendererModelOptions): {
  code: string;
  loading: boolean;
  isDisplayMode: boolean;
  error: boolean;
};
export declare function createMathRendererState(_?: Partial<MathRendererState>): MathRendererState;
export declare function createMermaidPreviewControllerState(_?: Partial<MermaidPreviewControllerState>): MermaidPreviewControllerState;
export declare function createMermaidPreviewModel(_: MermaidPreviewModelOptions): {
  code: string;
  loading: boolean;
  showControl: boolean;
  controlPosition: ZoomControlPosition;
  minHeight: number;
  height: string;
};
export declare function createMermaidRenderState(_?: Partial<MermaidRenderState>): MermaidRenderState;
export declare function createOverlayContainer(_: boolean): HTMLElement;
export declare function createPointerDraggedState(_: PointerEvent, _: ZoomPoint): Pick<ZoomState, 'translateX' | 'translateY'>;
export declare function createPointerDragStart(_: PointerEvent, _: ZoomState): ZoomPoint;
export declare function createPreviewSegmentedOptions(_: (_: string) => string): SelectOption[];
export declare function createRootStyle(_: Record<string, string>, _?: number | string): Record<string, string>;
export declare function createSegmentedModel<TStyle = Record<string, unknown>>(_: {
  options?: SelectOption[];
  value?: string;
  buttonStyle?: TStyle;
}): {
  value: string;
  items: SelectOption[];
  isActive(_: SelectOption): boolean;
  getButtonStyle(_: SelectOption): {
    paddingBlock: string;
    backgroundColor: string | undefined;
  };
};
export declare function createTableControlDescriptors(_: TableControlDescriptorOptions): ControlDescriptor[];
export declare function createTextAnimationScheduler(_?: AnimationTimeline): TextAnimationScheduler;
export declare function createTextParts(_: string, _?: string, _?: AnimationSplit): TextPart[];
export declare function createTouchMovedState({ rect, touches, touchState, options }: TouchZoomMoveInput): ZoomState;
export declare function createTouchZoomState({ state, rect, touches }: TouchZoomInput): TouchZoomState;
export declare function createWheelZoomState({ state, point, rect, deltaY, ctrlKey, metaKey, options }: WheelZoomInput): ZoomState | null;
export declare function createZoomContainerModel(_: {
  zoom: number;
  position: Parameters<typeof resolveZoomControlPosition>[0];
  controlSize?: 'vanilla' | 'large';
}): {
  zoomPercent: string;
  controlsPosition: ZoomControlPositionStyle;
  controlButtonProps: {
    iconWidth?: undefined;
    iconHeight?: undefined;
    buttonStyle?: undefined;
  } | {
    iconWidth: number;
    iconHeight: number;
    buttonStyle: {
      fontSize: string;
    };
  };
  controls: ControlDescriptor<UIStyleValue>[];
};
export declare function createZoomControlButtonProps(_?: 'vanilla' | 'large'): {
  iconWidth?: undefined;
  iconHeight?: undefined;
  buttonStyle?: undefined;
} | {
  iconWidth: number;
  iconHeight: number;
  buttonStyle: {
    fontSize: string;
  };
};
export declare function createZoomControlDescriptors(_: number, _?: 'vanilla' | 'large'): ControlDescriptor[];
export declare function createZoomPoint(_: number, _: number): ZoomPoint;
export declare function createZoomState(_?: ZoomOptions): ZoomState;
export declare function createZoomTransformStyle(_: ZoomState): {
  transform: string;
};
export declare function detectTextDirection(_: string): TextDirection;
export declare function dynamicImport<T>(_: string): Promise<T>;
export declare function ensureOverlayContainer(_: {
  isDark: boolean;
  cssVariables?: Record<string, string>;
}): HTMLElement | null;
export declare function escapeMarkdownTableCell(_: string): string;
export declare function extractTableDataFromElement(_: HTMLElement): TableData;
export declare function filterVisibleItems<T extends {
  visible?: (() => boolean) | undefined;
}>(_: T[]): T[];
export declare function flipImagePreviewHorizontal(_: ImagePreviewTransformState): ImagePreviewTransformState;
export declare function flipImagePreviewVertical(_: ImagePreviewTransformState): ImagePreviewTransformState;
export declare function getCodeDownloadOptions(_: string, _: boolean): SelectOption[];
export declare function getCodeFileExtension(_: string): string | undefined;
export declare function getConfigValue<T = unknown>(_: unknown, _: string): T | undefined;
export declare function getDocument(): Document | null;
export declare function getDocumentBody(_?: Document): HTMLElement | null;
export declare function getDocumentElement(_?: Document): HTMLElement | null;
export declare function getDownloadFilename(_: unknown, _: 'code' | 'table' | 'mermaid', _: string): string;
export declare function getHtmlPreviewMessageHeight(_: unknown, _?: number, _?: number): number | undefined;
export declare function getHtmlPreviewSandboxTokens(_: string): Set<string>;
export declare function getI18nText(_: unknown, _: string): string;
export declare function getIframeBodyHeight(_: HTMLIFrameElement | undefined, _?: number): number;
export declare function getModuleFromImport<T>(_: T, _: keyof Window | undefined): T | null;
export declare function getModuleStrategy(_?: ModuleStrategy | boolean): ModuleStrategy;
export declare function getOverlayContainer(): HTMLElement | null;
export declare function getSvgIntrinsicSize(_: SVGSVGElement): SvgIntrinsicSize | null;
export declare function getTableCellNodes<TNode = unknown>(_: TNode | {
  children?: TNode[];
}): TNode[];
export declare function getTableContent(_: TableFormat, _: TableData, _?: CSVSeparator): TableContent;
export declare function getTableCsvSeparator(_: unknown): CSVSeparator;
export declare function getTouchDistance(_: ZoomPoint, _: ZoomPoint): number;
export declare function getTransitionName(_: string): string;
export declare function handleCodeBlockControlAction(_: CodeBlockControlActionOptions): Promise<CodeBlockControlState>;
export declare function handleTableControlAction(_: TableControlActionOptions): Promise<TableControlState>;
export declare function isClickInsideFloating(_: Node, _?: HTMLElement, _?: HTMLElement): boolean;
export declare function isClient(): boolean;
export declare function isCodeOptionEnabled(_: unknown, _?: boolean): boolean;
export declare function isCodePreviewable<TComponent = unknown>(_: CodePreviewableOptions<TComponent>): boolean;
export declare function isConfigEnabled(_: unknown, _: string): boolean;
export declare function isDocumentElementDark(_?: Document, _?: string): boolean;
export declare function isElementInDocumentBody(_: Element, _?: Document): boolean;
export declare function isEscapeKeyEvent(_: Event): boolean;
export declare function isModuleEnabled(_?: ModuleStrategy | boolean): boolean;
export declare function isServer(): boolean;
export declare function isSupportedLanguage(_: string): language is SupportedLanguage;
export declare function isSupportESM(): boolean;
export declare function loadLocaleConfig(_: string | LocaleConfig): Promise<LocaleConfig>;
export declare function measureSvgContainerHeight(_: HTMLElement, _?: string): number | null;
export declare function mountMediumZoomClone(_: HTMLElement, _?: HTMLElement): boolean;
export declare function normalizeAnimationDuration(_: number | string | undefined): string | undefined;
export declare function normalizeCssSize(_: number | string | undefined): string | undefined;
export declare function normalizeThemeVariableValue(_: string): string | undefined;
export declare function openExternalUrl(_: string, _?: string): void;
export declare function playMediumZoomInClone(_: HTMLElement, _: string): void;
export declare function playMediumZoomOutClone(_: {
  cloned: HTMLElement;
  original: HTMLElement;
  zoomElement: HTMLElement;
  currentTransform: string;
}): void;
export declare function prepareMediumZoomInClone(_: HTMLElement, _: string): void;
export declare function prepareMediumZoomOutClone(_: {
  cloned: HTMLElement;
  zoomElement: HTMLElement;
  currentTransform: string;
}): void;
export declare function readDocumentLanguage(_?: Document): string;
export declare function readMediumZoomElementTransform(_: HTMLElement): string;
export declare function readThemeVariables(_?: HTMLElement): Record<string, string>;
export declare function removeTrailingSlash(_: string): string;
export declare function resetImagePreviewTransformState(): ImagePreviewTransformState;
export declare function resetZoomState(_?: ZoomOptions): ZoomState;
export declare function resolveAnimation(_?: AnimationType): AnimationType;
export declare function resolveAnimationSplit(_?: AnimationSplit): AnimationSplit;
export declare function resolveAnimationStagger(_?: number): number;
export declare function resolveCaret(_?: string): string | undefined;
export declare function resolveCodeLanguage(_?: string | null): string;
export declare function resolveCodeMaxHeight<TComponent = unknown>(_: CodeMaxHeightOptions<TComponent>): string | undefined;
export declare function resolveCodeOptions<TComponent = unknown>(_: CodeOptions<TComponent> | undefined, _: string): CodeOptionsLanguage<TComponent>;
export declare function resolveCodePreviewComponent<TComponent = unknown>(_: string, _: PreviewerConfig<TComponent> | undefined, _: Partial<Record<string, TComponent>>, _?: (_: unknown) => boolean): TComponent | undefined;
export declare function resolveEnableAnimate(_: StreamMarkdownMode, _?: boolean): boolean;
export declare function resolveEnableCaret(_: StreamMarkdownMode, _?: string): boolean;
export declare function resolveFloatingDelay(_?: FloatingDelay): {
  show: number;
  hide: number;
};
export declare function resolveGetter<T>(_: MaybeGetter<T> | undefined): T | undefined;
export declare function resolveHtmlPreviewAutoHeight<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined): boolean;
export declare function resolveHtmlPreviewHeight<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined): string;
export declare function resolveHtmlPreviewMaxHeight<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined): string | undefined;
export declare function resolveHtmlPreviewMaxHeightValue<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined): number | undefined;
export declare function resolveHtmlPreviewMeasurementMode(_: string, _: boolean): HtmlPreviewMeasurementMode;
export declare function resolveHtmlPreviewSandbox<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined): string;
export declare function resolveImageControlPosition(_: unknown): ZoomControlPosition;
export declare function resolveLinkFaviconUrl(_: string, _?: LinkOptions['favicon']): Promise<string | undefined> | string | undefined;
export declare function resolveLocaleInput(_: string | LocaleConfig | undefined, _?: {
  htmlLanguage?: string;
  navigatorLanguage?: string;
}): string | LocaleConfig;
export declare function resolveLocaleLanguage(_: string | LocaleConfig): SupportedLanguage;
export declare function resolveMermaidContainerHeight(_?: number | string, _?: number): string;
export declare function resolveMermaidControlPosition(_: unknown): ZoomControlPosition;
export declare function resolveMermaidInlineInteractive(_: unknown): boolean;
export declare function resolvePreviewPlacement<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined, _: boolean): PreviewSegmentedPlacement;
export declare function resolveScrollableMaxHeight(_: number | string | undefined): string | undefined;
export declare function resolveSupportedLanguage(_?: string): SupportedLanguage;
export declare function resolveTableAlign(_: Array<TableAlign | null | undefined> | undefined, _: number): TableAlign;
export declare function resolveTextAnimationSplit(_: string, _?: AnimationSplit): ResolvedAnimationSplit;
export declare function resolveTextDirection(_: string, _: TextDirectionConfig | undefined): TextDirection | undefined;
export declare function resolveThemeElement(_?: () => HTMLElement | undefined): HTMLElement | undefined;
export declare function resolveThemeVariables(_: readonly string[], _: (_: string) => string): Record<string, string>;
export declare function resolveVisibleControls<TControl extends {
  visible?: (() => boolean) | undefined;
}, TProps>(_: unknown, _: string, _: TControl[], _: TProps): TControl[];
export declare function resolveZoomControlPosition(_: ZoomControlPosition): ZoomControlPositionStyle;
export declare function resolveZoomOptions(_?: ZoomOptions): Required<ZoomOptions>;
export declare function rotateImagePreviewLeft(_: ImagePreviewTransformState): ImagePreviewTransformState;
export declare function rotateImagePreviewRight(_: ImagePreviewTransformState): ImagePreviewTransformState;
export declare function save(_: string, _: string | Blob, _: string): void;
export declare function saveImage(_: string, _?: string): Promise<void>;
export declare function scrollToElement(_: ParentNode, _: string, _?: ScrollIntoViewOptions): boolean;
export declare function serializeSvgForDownload(_: string): string;
export declare function setMediumZoomOriginalVisibility(_: HTMLElement, _: boolean): void;
export declare function setMermaidMeasuredHeight(_: MermaidPreviewControllerState, _: number): MermaidPreviewControllerState;
export declare function setZoomState(_: ZoomState, _: number, _?: ZoomOptions): ZoomState;
export declare function shouldEagerRenderMermaidAfterLoading(_: MermaidRenderState, _: boolean, _: boolean | undefined): boolean;
export declare function shouldProgressivelyRenderPreview<TComponent = unknown>(_: PreviewerConfig<TComponent> | undefined, _: string): boolean;
export declare function splitText(_: string, _?: AnimationSplit): string[];
export declare function splitTextByAuto(_: string): string[];
export declare function splitTextByChar(_: string): string[];
export declare function splitTextByWord(_: string): string[];
export declare function startMermaidRenderAttempt(_: MermaidPreviewControllerState): MermaidPreviewControllerState;
export declare function startMermaidRenderAttempt(_: MermaidRenderState): MermaidRenderState;
export declare function stripVersionRangePrefix(_: string): string;
export declare function svgToPngBlob(_: string, _?: {
  scale?: number;
}): Promise<Blob> | null;
export declare function syncCodeBlockMode(_: CodeBlockModeState, _: boolean): CodeBlockModeState;
export declare function syncOverlayContainerTheme(_: HTMLElement | null, _: {
  isDark: boolean;
  cssVariables?: Record<string, string>;
}): void;
export declare function tableDataToCSV(_: TableData, _?: CSVSeparator): string;
export declare function tableDataToMarkdown(_: TableData): string;
export declare function tableDataToTSV(_: TableData): string;
export declare function transformHardenedUrl<TComponent = unknown>(_: string | undefined, _?: HardenOptions<TComponent>, _?: {
  defaults?: HardenOptions<TComponent>;
  isImage?: boolean;
  loading?: boolean;
}): string | null;
export declare function transformUrl(_: unknown, _: string[], _: string, _?: boolean, _?: boolean, _?: string[]): string | null;
export declare function unmountMediumZoomClone(_: HTMLElement): void;
export declare function zoomInState(_: ZoomState, _?: ZoomOptions): ZoomState;
export declare function zoomOutState(_: ZoomState, _?: ZoomOptions): ZoomState;
// #endregion

// #region Variables
export declare const ANIMATION_SPLITS: readonly ['auto', 'word', 'char'];
export declare const ANIMATION_TYPES: readonly ['fade-in', 'blur-in', 'slide-up'];
export declare const CARETS: {
  readonly block: ' ▋';
  readonly circle: ' ●';
};
export declare const CODE_META_NO_LINE_NUMBERS_PATTERN: RegExp;
export declare const CODE_META_START_LINE_PATTERN: RegExp;
export declare const DEFAULT_ANIMATION: "fade-in";
export declare const DEFAULT_ANIMATION_SPLIT: "auto";
export declare const DEFAULT_ANIMATION_STAGGER: number;
export declare const DEFAULT_HARDEN_OPTIONS: HardenOptions;
export declare const DEFAULT_HTML_PREVIEW_HEIGHT: number;
export declare const DEFAULT_HTML_PREVIEW_SANDBOX: string;
export declare const DEFAULT_LANGUAGE: SupportedLanguage;
export declare const DEFAULT_SHIKI_DARK_THEME: string;
export declare const DEFAULT_SHIKI_LIGHT_THEME: string;
export declare const DISABLED_TRANSITION_NAME: string;
export declare const HTML_PREVIEW_HEIGHT_MESSAGE_TYPE: string;
export declare const LANGUAGE_ALIAS: Record<string, string>;
export declare const LANGUAGE_EXTENSIONS: Record<string, string>;
export declare const MAX_HTML_PREVIEW_AUTO_HEIGHT: number;
export declare const OVERLAY_CONTAINER_ID: string;
export declare const SHADCN_SCHEMAS: readonly ['background', 'foreground', 'card', 'card-foreground', 'popover', 'popover-foreground', 'primary', 'primary-foreground', 'secondary', 'secondary-foreground', 'muted', 'muted-foreground', 'accent', 'accent-foreground', 'destructive', 'border', 'input', 'ring', 'chart-1', 'chart-2', 'chart-3', 'chart-4', 'chart-5', 'sidebar', 'sidebar-foreground', 'sidebar-primary', 'sidebar-primary-foreground', 'sidebar-accent', 'sidebar-accent-foreground', 'sidebar-border', 'sidebar-ring'];
export declare const STREAM_MARKDOWN_CSS_VARIABLES: {
  readonly animationDuration: '--stream-markdown-animation-duration';
  readonly defaultTransitionDuration: '--default-transition-duration';
};
export declare const STREAM_MARKDOWN_PREFIX: string;
export declare const SUPPORT_LANGUAGES: SupportedLanguage[];
export declare const TABLE_FORMAT_OPTIONS: SelectOption[];
// #endregion