/**
 * Generated by tsnapi — public API snapshot of `@markmend/parser`
 */
// #region Interfaces
export interface CreateMarkmendParserOptions {
  completion?: Completion;
  literalTagContent?: string[];
  parserOptions?: MarkmendParserOptions;
  syntax?: MarkmendSyntaxOptions;
}
export interface MarkmendParser {
  getDocument: () => MarkdownDocument$1;
  parse: (_: string, _?: MarkdownMode) => Promise<MarkmendParseResult>;
}
export interface MarkmendParseResult {
  completion?: CompletionInfo;
  document: MarkdownDocument$1;
}
export interface MarkmendSyntaxOptions {
  cjk?: boolean;
  footnotes?: false | FootnotesConfig;
  security?: false | SecurityOptions;
}
// #endregion

// #region Types
export type Completion = boolean | CompletionOptions | CompletionFunction;
export type CompletionFunction = (_: string) => CompletionResult | string;
export type MarkdownMode = 'static' | 'streaming';
export type MarkmendParserOptions<TPlugins extends readonly ComarkPlugin<any, any>[] = readonly ComarkPlugin<any, any>[]> = Omit<ParserOptions<TPlugins>, 'autoClose'>;
export type SecurityOptions = NonNullable<Parameters<typeof security>[0]>;
// #endregion

// #region Functions
export declare function createMarkmendParser(_?: CreateMarkmendParserOptions): MarkmendParser;
// #endregion

// #region Re-exports
export * from "@markmend/core";
// #endregion

// #region Other
export { ComarkPlugin }
export { ElementNode }
export { MarkdownDocument }
export { Node as MarkdownNode }
export { Node$1 as Node }
export { ParserOptions }
// #endregion