/**
 * Generated by tsnapi — public API snapshot of `@stream-markdown/beautiful-mermaid`
 */
// #region Interfaces
export interface BeautifulMermaidCdnLoaderOptions {
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
}
export interface BeautifulMermaidExtensionOptions<TErrorComponent = never> extends BeautifulMermaidRuntimeOptions {
  errorComponent?: TErrorComponent;
}
export interface BeautifulMermaidRuntime {
  preload: () => Promise<void>;
  load: () => Promise<typeof import('beautiful-mermaid')>;
  dispose: () => void;
  supports: (_: string) => boolean;
  render: (_: MermaidRenderInput) => Promise<MermaidExtensionRenderResult>;
}
export interface BeautifulMermaidRuntimeOptions {
  cdnOptions?: MaybeGetter<SharedCdnOptions | undefined>;
  config?: MaybeGetter<RenderOptions$1 | undefined>;
  theme?: MaybeGetter<[ThemeName$1, ThemeName$1] | undefined>;
}
// #endregion

// #region Functions
export declare function beautifulMermaid<TErrorComponent = never>(_?: BeautifulMermaidExtensionOptions<TErrorComponent>): MermaidExtension<TErrorComponent>;
export declare function createBeautifulMermaidCdnLoader(_?: BeautifulMermaidCdnLoaderOptions): {
  getCdnUrl: () => string | undefined;
  loadCdn: () => Promise<typeof import('beautiful-mermaid') | undefined>;
};
export declare function createBeautifulMermaidRuntime(_?: BeautifulMermaidRuntimeOptions): BeautifulMermaidRuntime;
// #endregion

// #region Variables
export declare const BEAUTIFUL_MERMAID_SUPPORTED_PATTERNS: readonly ['flowchart', 'graph', 'stateDiagram', 'sequence', 'classDiagram', 'erDiagram', 'xychart'];
export declare const BEAUTIFUL_MERMAID_VERSION: string;
export declare const DEFAULT_BEAUTIFUL_MERMAID_THEME: [ThemeName$1, ThemeName$1];
export declare const PRESET_BEAUTIFUL_MERMAID_CONFIG: RenderOptions$1;
// #endregion

// #region Other
export { RenderOptions }
export { ThemeName }
// #endregion