/**
 * Generated by tsnapi — public API snapshot of `@markmend/core`
 */
// #region Interfaces
export interface CompletionInfo {
  phase?: string;
  type: CompletionType;
}
export interface CompletionOptions {
  comparisonOperators?: boolean;
  hideBareFormattingMarkers?: boolean;
  completionSteps?: CompletionSteps;
  singleDollarTextMath?: boolean;
}
export interface CompletionResult {
  completion?: CompletionInfo;
  markdown: string;
}
// #endregion

// #region Types
export type BuiltinCompletionType = 'code' | 'comparisonOperators' | 'html' | 'footnote' | 'strong' | 'emphasis' | 'delete' | 'taskList' | 'link' | 'table' | 'inlineMath' | 'math';
export type CompletionStep = (_: string, _?: CompletionContext) => string;
export type CompletionSteps = Partial<Record<BuiltinCompletionType, CompletionStep>>;
export type CompletionType = BuiltinCompletionType | (string & {});
// #endregion

// #region Functions
export declare function completeCode(_: string): string;
export declare function completeComparisonOperators(_: string, _?: Pick<CompletionContext, 'comparisonOperators'>): string;
export declare function completeDelete(_: string, _?: CompletionContext): string;
export declare function completeEmphasis(_: string, _?: CompletionContext): string;
export declare function completeFootnote(_: string, _?: CompletionContext): string;
export declare function completeHtml(_: string, _?: CompletionContext): string;
export declare function completeInlineMath(_: string, _?: CompletionContext): string;
export declare function completeLink(_: string, _?: CompletionContext): string;
export declare function completeMarkdown(_: string, _?: CompletionOptions): string;
export declare function completeMarkdownResult(_: string, _?: CompletionOptions): CompletionResult;
export declare function completeMath(_: string, _?: CompletionContext): string;
export declare function completeStrong(_: string, _?: CompletionContext): string;
export declare function completeTable(_: string, _?: CompletionContext): string;
export declare function completeTaskList(_: string, _?: CompletionContext): string;
// #endregion

// #region Variables
export declare const defaultCompletionSteps: {
  code: typeof completeCode;
  comparisonOperators: typeof completeComparisonOperators;
  html: typeof completeHtml;
  footnote: typeof completeFootnote;
  strong: typeof completeStrong;
  emphasis: typeof completeEmphasis;
  delete: typeof completeDelete;
  taskList: typeof completeTaskList;
  link: typeof completeLink;
  table: typeof completeTable;
  inlineMath: typeof completeInlineMath;
  math: typeof completeMath;
};
// #endregion

// #region Referenced (internal)
type CompletionContext = CompletionOptions;
// #endregion