/**
 * Generated by tsnapi — public API snapshot of `@markmend/core`
 */
// #region Interfaces
export interface CompletionInfo {
  phase?: string;
  type: CompletionType;
}
export interface CompletionOptions {
  comparisonOperators?: boolean;
  hideBareFormattingMarkers?: boolean;
  singleDollarTextMath?: boolean;
}
export interface CompletionResult {
  completion?: CompletionInfo;
  markdown: string;
}
// #endregion

// #region Types
export type BuiltinCompletionType = 'code' | 'comparisonOperators' | 'html' | 'footnote' | 'strong' | 'emphasis' | 'delete' | 'taskList' | 'link' | 'table' | 'inlineMath' | 'math';
export type CompletionType = BuiltinCompletionType | (string & {});
// #endregion

// #region Functions
export declare function completeMarkdown(_: string, _?: CompletionOptions): string;
export declare function completeMarkdownResult(_: string, _?: CompletionOptions): CompletionResult;
// #endregion